export const nutriFood_Chat = [
    {
        name: 'abalone',
        serving_size_g: 100,
        calories: 105,
        protein_g: 17.6,
        fat_total_g: 1.2,
        fat_saturated_g: 0,
        cholesterol_mg: 52,
        carbohydrates_total_g: 3.2,
        fiber_g: 0,
        sugar_g: 0,
        sodium_mg: 483,
        potassium_mg: 131
    },
    {
        name: 'abbaye de belloc',
        serving_size_g: 100,
        calories: 382,
        protein_g: 24,
        fat_total_g: 31,
        fat_saturated_g: 22,
        cholesterol_mg: 82,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        sodium_mg: 620,
        potassium_mg: 100
    },
    {
        name: 'abbaye de citeaux',
        serving_size_g: 100,
        calories: 359,
        protein_g: 22,
        fat_total_g: 29,
        fat_saturated_g: 18,
        cholesterol_mg: 99,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        sodium_mg: 796,
        potassium_mg: 71
    },
    {
        name: 'abbaye du mont des cats',
        serving_size_g: 100,
        calories: 338,
        protein_g: 21,
        fat_total_g: 27,
        fat_saturated_g: 16,
        cholesterol_mg: 75,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        sodium_mg: 550,
        potassium_mg: 100
    },
    {
        name: 'abertam',
        serving_size_g: 100,
        calories: 363,
        protein_g: 25,
        fat_total_g: 28,
        fat_saturated_g: 19,
        cholesterol_mg: 75,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        sodium_mg: 570,
        potassium_mg: 96
    },
    {
        name: 'abiu',
        serving_size_g: 100,
        calories: 67,
        protein_g: 1.1,
        fat_total_g: 0.2,
        fat_saturated_g: 0,
        cholesterol_mg: 0,
        carbohydrates_total_g: 16.3,
        fiber_g: 4.3,
        sugar_g: 11.9,
        sodium_mg: 0,
        potassium_mg: 62
    },
    {
        name: 'abondance',
        serving_size_g: 100,
        calories: 387,
        protein_g: 25,
        fat_total_g: 32,
        fat_saturated_g: 21,
        cholesterol_mg: 95,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        sodium_mg: 540,
        potassium_mg: 100
    },
    {
        name: 'absolut',
        serving_size_g: 100,
        calories: 231,
        fat_total_g: 0,
        fat_saturated_g: 0,
        cholesterol_mg: 0,
        sodium_mg: 0,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 0,
        potassium_mg: 0
    },
    {
        name: 'aburana',
        serving_size_g: 100,
        calories: 522,
        fat_total_g: 28.5,
        fat_saturated_g: 7.6,
        cholesterol_mg: 0,
        sodium_mg: 0,
        carbohydrates_total_g: 64.8,
        fiber_g: 4.4,
        sugar_g: 0,
        protein_g: 7.4,
        potassium_mg: 303
    },
    {
        name: 'açaí',
        serving_size_g: 100,
        calories: 70,
        fat_total_g: 5,
        fat_saturated_g: 1.2,
        cholesterol_mg: 0,
        sodium_mg: 4,
        carbohydrates_total_g: 4,
        fiber_g: 2,
        sugar_g: 2,
        protein_g: 1,
        potassium_mg: 106
    },
    {
        name: 'acapella',
        serving_size_g: 100,
        calories: 263,
        fat_total_g: 23,
        fat_saturated_g: 9.6,
        cholesterol_mg: 29,
        sodium_mg: 800,
        carbohydrates_total_g: 3.7,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 11,
        potassium_mg: 0
    },
    {
        name: 'acém',
        serving_size_g: 100,
        calories: 194,
        fat_total_g: 10.7,
        fat_saturated_g: 3.8,
        cholesterol_mg: 54,
        sodium_mg: 60,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 22,
        potassium_mg: 262
    },
    {
        name: 'acerola',
        serving_size_g: 100,
        calories: 32,
        fat_total_g: 0.3,
        fat_saturated_g: 0,
        cholesterol_mg: 0,
        sodium_mg: 7,
        carbohydrates_total_g: 7.7,
        fiber_g: 1.1,
        sugar_g: 0,
        protein_g: 0.4,
        potassium_mg: 146
    },
    {
        name: 'ackawi',
        serving_size_g: 100,
        calories: 364,
        fat_total_g: 26,
        fat_saturated_g: 17,
        cholesterol_mg: 61,
        sodium_mg: 1000,
        carbohydrates_total_g: 4,
        fiber_g: 0,
        sugar_g: 4,
        protein_g: 28,
        potassium_mg: 0
    },
    {
        sugar_g: null,
        fiber_g: 6.7,
        serving_size_g: 100,
        sodium_mg: 0,
        name: 'acorn',
        potassium_mg: 0,
        fat_saturated_g: 0.9,
        fat_total_g: 23.8,
        calories: 387,
        cholesterol_mg: 0,
        protein_g: 6.2,
        carbohydrates_total_g: 40.1,
    },
    {
        sugar_g: null,
        fiber_g: null,
        serving_size_g: 100,
        sodium_mg: 690,
        name: 'adelost',
        potassium_mg: null,
        fat_saturated_g: 16.6,
        fat_total_g: 29.3,
        calories: 355,
        cholesterol_mg: 46,
        protein_g: 23.5,
        carbohydrates_total_g: 0.8,
    },
    {
        name: 'alaminos longganisa',
        serving_size_g: 100,
        calories: 300,
        fat_total_g: 25,
        fat_saturated_g: 8,
        cholesterol_mg: 50,
        sodium_mg: 700,
        carbohydrates_total_g: 3,
        fiber_g: 0,
        sugar_g: 2,
        protein_g: 15,
        potassium_mg: 200,
    },
    {
        name: 'albariño',
        serving_size_g: 100,
        calories: 83,
        fat_total_g: 0,
        fat_saturated_g: 0,
        cholesterol_mg: 0,
        sodium_mg: 8,
        carbohydrates_total_g: 3.5,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 0.1,
        potassium_mg: 92,
    },
    {
        name: 'alcatra',
        serving_size_g: 100,
        calories: 270,
        fat_total_g: 20,
        fat_saturated_g: 7,
        cholesterol_mg: 80,
        sodium_mg: 70,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 22,
        potassium_mg: 310,
    },
    {
        name: 'alfalfa sprouts',
        serving_size_g: 100,
        calories: 23,
        fat_total_g: 0.7,
        fat_saturated_g: 0.1,
        cholesterol_mg: 0,
        sodium_mg: 6,
        carbohydrates_total_g: 2.1,
        fiber_g: 1.9,
        sugar_g: 0.4,
        protein_g: 3.9,
        potassium_mg: 79,
    },
    {
        name: 'alheira',
        serving_size_g: 100,
        calories: 250,
        fat_total_g: 15,
        fat_saturated_g: 4.2,
        cholesterol_mg: 75,
        sodium_mg: 820,
        carbohydrates_total_g: 14,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 14,
        potassium_mg: 0,
    },
    {
        name: 'allgauer emmentaler',
        serving_size_g: 100,
        calories: 400,
        fat_total_g: 32,
        fat_saturated_g: 20,
        cholesterol_mg: 100,
        sodium_mg: 700,
        carbohydrates_total_g: 1,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 27,
        potassium_mg: 120,
    },
    {
        name: 'american elderberry',
        calories: 73,
        fat_total_g: 0.5,
        cholesterol_mg: 0,
        sodium_mg: 6,
        potassium_mg: 280,
        carbohydrates_total_g: 18.4,
        fiber_g: 7,
        sugar_g: 10.2,
        protein_g: 0.7,
        serving_size_g: 100
    },
    {
        name: 'ami du chambertin',
        calories: 360,
        fat_total_g: 29,
        cholesterol_mg: 100,
        sodium_mg: 520,
        potassium_mg: 100,
        carbohydrates_total_g: 0.5,
        fiber_g: 0,
        sugar_g: 0.5,
        protein_g: 24,
        serving_size_g: 100
    },
    {
        name: 'ananas',
        calories: 50,
        fat_total_g: 0.1,
        cholesterol_mg: 0,
        sodium_mg: 1,
        potassium_mg: 180,
        carbohydrates_total_g: 13,
        fiber_g: 1.4,
        sugar_g: 9.8,
        protein_g: 0.5,
        serving_size_g: 100
    },
    {
        name: 'andouillette',
        calories: 360,
        fat_total_g: 35,
        cholesterol_mg: 80,
        sodium_mg: 1150,
        potassium_mg: 0,
        carbohydrates_total_g: 2,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 10,
        serving_size_g: 100
    },
    {
        name: 'anglerfish',
        serving_size_g: 100,
        calories: 72,
        fat_total_g: 0.9,
        fat_saturated_g: 0.2,
        cholesterol_mg: 22,
        sodium_mg: 85,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 16.2,
        potassium_mg: 400
    },
    {
        name: 'annatto',
        serving_size_g: 100,
        calories: 519,
        fat_total_g: 44.2,
        fat_saturated_g: 13.4,
        cholesterol_mg: 0,
        sodium_mg: 0,
        carbohydrates_total_g: 23.4,
        fiber_g: 12.5,
        sugar_g: 0,
        protein_g: 13.5,
        potassium_mg: 1250
    },
    {
        name: 'Aperol',
        serving_size_g: 60,
        calories: 105,
        fat_total_g: 0,
        fat_saturated_g: 0,
        cholesterol_mg: 0,
        sodium_mg: 0,
        carbohydrates_total_g: 6.6,
        fiber_g: 0,
        sugar_g: 6.6,
        protein_g: 0,
        potassium_mg: 25
    },
    {
        name: 'appenzell',
        serving_size_g: 100,
        calories: 388,
        fat_total_g: 31,
        fat_saturated_g: 18,
        cholesterol_mg: 85,
        sodium_mg: 1000,
        carbohydrates_total_g: 2.4,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 23,
        potassium_mg: 0
    },
    {
        name: 'arabiki',
        serving_size_g: 100,
        calories: 243,
        fat_total_g: 13,
        fat_saturated_g: 4.7,
        cholesterol_mg: 0,
        sodium_mg: 36,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 31,
        potassium_mg: 0
    },
    {
        name: 'aragon',
        serving_size_g: 100,
        calories: 393,
        fat_total_g: 32,
        fat_saturated_g: 16,
        cholesterol_mg: 80,
        sodium_mg: 0,
        carbohydrates_total_g: 1,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 25,
        potassium_mg: 0
    },
    {
        name: 'araza',
        serving_size_g: 100,
        calories: 80,
        fat_total_g: 1.2,
        fat_saturated_g: 0.5,
        cholesterol_mg: 0,
        sodium_mg: 4,
        carbohydrates_total_g: 18.6,
        fiber_g: 4.6,
        sugar_g: 7.8,
        protein_g: 1.9,
        potassium_mg: 358
    },
    {
        name: 'ardi gasna',
        serving_size_g: 100,
        calories: 356,
        fat_total_g: 30,
        fat_saturated_g: 20,
        cholesterol_mg: 75,
        sodium_mg: 0,
        carbohydrates_total_g: 1,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 21,
        potassium_mg: 0
    },
    {
        name: 'ardrahan',
        serving_size_g: 100,
        calories: 364,
        fat_total_g: 31,
        fat_saturated_g: 22,
        cholesterol_mg: 0,
        sodium_mg: 1000,
        carbohydrates_total_g: 0.5,
        fiber_g: 0,
        sugar_g: 0.5,
        protein_g: 21,
        potassium_mg: 0
    },
    {
        name: 'arhat',
        serving_size_g: 100,
        calories: 105,
        fat_total_g: 1.7,
        fat_saturated_g: 0.2,
        cholesterol_mg: 0,
        sodium_mg: 8,
        carbohydrates_total_g: 20.4,
        fiber_g: 6.8,
        sugar_g: 4.3,
        protein_g: 3.6,
        potassium_mg: 170
    },
    {
        name: 'asadero',
        serving_size_g: 100,
        calories: 356,
        fat_total_g: 28,
        fat_saturated_g: 17,
        cholesterol_mg: 95,
        sodium_mg: 580,
        carbohydrates_total_g: 2.8,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 24,
        potassium_mg: 240
    },
    {
        name: 'asafoetida',
        serving_size_g: 1,
        calories: 3.6,
        fat_total_g: 0.1,
        fat_saturated_g: 0,
        cholesterol_mg: 0,
        sodium_mg: 9,
        carbohydrates_total_g: 0.9,
        fiber_g: 0.6,
        sugar_g: 0.1,
        protein_g: 0.2,
        potassium_mg: 24
    },
    {
        name: 'ash gourd',
        serving_size_g: 100,
        calories: 13,
        fat_total_g: 0.2,
        fat_saturated_g: 0,
        cholesterol_mg: 0,
        sodium_mg: 5,
        carbohydrates_total_g: 2.4,
        fiber_g: 1.2,
        sugar_g: 1,
        protein_g: 0.6,
        potassium_mg: 200
    },
    {
        name: 'asiago cheese',
        serving_size_g: 28,
        calories: 110,
        fat_total_g: 9,
        fat_saturated_g: 6,
        cholesterol_mg: 30,
        sodium_mg: 190,
        carbohydrates_total_g: 1,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 7,
        potassium_mg: 20
    },
    {
        name: 'atemoya',
        serving_size_g: 100,
        calories: 94,
        fat_total_g: 0.2,
        fat_saturated_g: 0.1,
        cholesterol_mg: 0,
        sodium_mg: 3,
        carbohydrates_total_g: 23.6,
        fiber_g: 3.3,
        sugar_g: 21.4,
        protein_g: 1.7,
        potassium_mg: 278
    },
    {
        name: 'azuki bean',
        serving_size_g: 100,
        calories: 333,
        fat_total_g: 0.5,
        fat_saturated_g: 0.1,
        cholesterol_mg: 0,
        sodium_mg: 2,
        carbohydrates_total_g: 63.4,
        fiber_g: 25.7,
        sugar_g: 2.3,
        protein_g: 23.5,
        potassium_mg: 1800
    },
    {
        name: 'azuki beans',
        serving_size_g: 100,
        calories: 333,
        fat_total_g: 0.5,
        fat_saturated_g: 0.1,
        cholesterol_mg: 0,
        sodium_mg: 2,
        carbohydrates_total_g: 63.4,
        fiber_g: 25.7,
        sugar_g: 2.3,
        protein_g: 23.5,
        potassium_mg: 1800
    },
    {
        name: 'baby swiss',
        serving_size_g: 28,
        calories: 110,
        fat_total_g: 9,
        fat_saturated_g: 6,
        cholesterol_mg: 30,
        sodium_mg: 50,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 7,
        potassium_mg: 0
    },
    {
        name: 'bakers',
        serving_size_g: 100,
        calories: 259,
        fat_total_g: 1.3,
        fat_saturated_g: 0.3,
        cholesterol_mg: 0,
        sodium_mg: 3,
        carbohydrates_total_g: 53.4,
        fiber_g: 4.4,
        sugar_g: 1.8,
        protein_g: 10.4,
        potassium_mg: 310
    },
    {
        name: 'baladi',
        serving_size_g: 100,
        calories: 139,
        fat_total_g: 0.9,
        fat_saturated_g: 0.2,
        cholesterol_mg: 0,
        sodium_mg: 4,
        carbohydrates_total_g: 25.8,
        fiber_g: 4.1,
        sugar_g: 9.9,
        protein_g: 9.1,
        potassium_mg: 496
    },
    {
        name: 'balaton',
        serving_size_g: 100,
        calories: 72,
        fat_total_g: 0.6,
        fat_saturated_g: 0.1,
        cholesterol_mg: 0,
        sodium_mg: 1,
        carbohydrates_total_g: 14.7,
        fiber_g: 3.9,
        sugar_g: 0.7,
        protein_g: 3.3,
        potassium_mg: 358
    },
    {
        name: 'bambara beans',
        serving_size_g: 100,
        calories: 147,
        fat_total_g: 1.1,
        fat_saturated_g: 0.2,
        cholesterol_mg: 0,
        sodium_mg: 0,
        carbohydrates_total_g: 27.7,
        fiber_g: 2.2,
        sugar_g: 1.1,
        protein_g: 8.3,
        potassium_mg: 610
    },
    {
        name: 'banana squash',
        serving_size_g: 100,
        calories: 27,
        fat_total_g: 0.1,
        fat_saturated_g: 0,
        cholesterol_mg: 0,
        sodium_mg: 2,
        carbohydrates_total_g: 6.5,
        fiber_g: 1.8,
        sugar_g: 2.8,
        protein_g: 0.8,
        potassium_mg: 321
    },
    {
        name: 'banat sausage',
        serving_size_g: 100,
        calories: 377,
        fat_total_g: 30.9,
        fat_saturated_g: 13.4,
        cholesterol_mg: 75,
        sodium_mg: 1784,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 23.4,
        potassium_mg: 328
    },
    {
        name: 'banon',
        serving_size_g: 100,
        calories: 321,
        fat_total_g: 29.2,
        fat_saturated_g: 20.5,
        cholesterol_mg: 67,
        sodium_mg: 455,
        carbohydrates_total_g: 0.5,
        fiber_g: 0,
        sugar_g: 0.5,
        protein_g: 14.8,
        potassium_mg: 277
    },
    {
        name: 'barbadine',
        serving_size_g: 100,
        calories: 64,
        fat_total_g: 0.1,
        fat_saturated_g: 0,
        cholesterol_mg: 0,
        sodium_mg: 3,
        carbohydrates_total_g: 16.4,
        fiber_g: 2.4,
        sugar_g: 13.8,
        protein_g: 1.2,
        potassium_mg: 123
    },
    {
        name: 'barbados cherry',
        serving_size_g: 100,
        calories: 32,
        fat_total_g: 0.3,
        fat_saturated_g: 0.1,
        cholesterol_mg: 0,
        sodium_mg: 7,
        carbohydrates_total_g: 7.7,
        fiber_g: 1.1,
        sugar_g: 3.2,
        protein_g: 0.4,
        potassium_mg: 146
    },
    {
        name: 'barberry',
        serving_size_g: 100,
        calories: 196,
        fat_total_g: 1.5,
        fat_saturated_g: 0.3,
        cholesterol_mg: 0,
        sodium_mg: 49,
        carbohydrates_total_g: 45.9,
        fiber_g: 4.3,
        sugar_g: 19.7,
        protein_g: 3.2,
        potassium_mg: 231
    },
    {
        name: 'barley',
        serving_size_g: 100,
        calories: 354,
        fat_total_g: 2.3,
        fat_saturated_g: 0.4,
        cholesterol_mg: 0,
        sodium_mg: 12,
        carbohydrates_total_g: 73.5,
        fiber_g: 17.3,
        sugar_g: 0.8,
        protein_g: 12.5,
        potassium_mg: 452
    },
    {
        name: 'barley grass',
        serving_size_g: 100,
        calories: 216,
        fat_total_g: 0.7,
        fat_saturated_g: 0.2,
        cholesterol_mg: 0,
        sodium_mg: 70,
        carbohydrates_total_g: 18.1,
        fiber_g: 30.1,
        sugar_g: 0.9,
        protein_g: 30.6,
        potassium_mg: 3700
    },
    {
        name: "basing",
        serving_size_g: 100,
        calories: 253,
        fat_total_g: 20.5,
        fat_saturated_g: 12.9,
        cholesterol_mg: 75,
        sodium_mg: 554,
        carbohydrates_total_g: 4.2,
        fiber_g: 0,
        sugar_g: 1.6,
        protein_g: 13.5,
        potassium_mg: 90
    },
    {
        name: 'bergader',
        serving_size_g: 100,
        calories: 400,
        fat_total_g: 34,
        fat_saturated_g: 23,
        cholesterol_mg: 105,
        sodium_mg: 700,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 25,
        potassium_mg: 0
    },
    {
        name: 'bergamot',
        serving_size_g: 100,
        calories: 43,
        fat_total_g: 0.8,
        fat_saturated_g: 0.2,
        cholesterol_mg: 0,
        sodium_mg: 1,
        carbohydrates_total_g: 11,
        fiber_g: 1.1,
        sugar_g: 4.4,
        protein_g: 0.8,
        potassium_mg: 350
    },
    {
        name: 'bergere bleue',
        serving_size_g: 100,
        calories: 375,
        fat_total_g: 30,
        fat_saturated_g: 20,
        cholesterol_mg: 80,
        sodium_mg: 580,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 25,
        potassium_mg: 0
    },
    {
        name: 'berkswell',
        serving_size_g: 100,
        calories: 387,
        fat_total_g: 31,
        fat_saturated_g: 22,
        cholesterol_mg: 89,
        sodium_mg: 600,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 27,
        potassium_mg: 0
    },
    {
        name: 'betel nut',
        serving_size_g: 100,
        calories: 389,
        fat_total_g: 1,
        fat_saturated_g: 0,
        cholesterol_mg: 0,
        sodium_mg: 20,
        carbohydrates_total_g: 85,
        fiber_g: 9,
        sugar_g: 0,
        protein_g: 6.7,
        potassium_mg: 410
    },
    {
        name: 'betel',
        serving_size_g: 100,
        calories: 100,
        fat_total_g: 1.2,
        fat_saturated_g: 0.6,
        cholesterol_mg: 0,
        sodium_mg: 0,
        carbohydrates_total_g: 23.9,
        fiber_g: 4.3,
        sugar_g: 14.1,
        protein_g: 3.4,
        potassium_mg: 141
    },
    {
        name: 'bethmale des pyrénées',
        calories: 367,
        fat_total_g: 28,
        fat_saturated_g: 20,
        cholesterol_mg: 98,
        sodium_mg: 740,
        carbohydrates_total_g: 1,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 25,
        serving_size_g: 100,
        potassium_mg: 0
    },
    {
        name: 'bethmale of the pyrenees',
        calories: 367,
        fat_total_g: 28,
        fat_saturated_g: 20,
        cholesterol_mg: 98,
        sodium_mg: 740,
        carbohydrates_total_g: 1,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 25,
        serving_size_g: 100,
        potassium_mg: 0
    },
    {
        name: 'beutelwurst',
        calories: 304,
        fat_total_g: 28,
        fat_saturated_g: 10,
        cholesterol_mg: 45,
        sodium_mg: 640,
        carbohydrates_total_g: 1,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 12,
        serving_size_g: 100,
        potassium_mg: 0
    },
    {
        name: 'beyaz peynir',
        calories: 316,
        fat_total_g: 25,
        fat_saturated_g: 17,
        cholesterol_mg: 60,
        sodium_mg: 1530,
        carbohydrates_total_g: 3,
        fiber_g: 0,
        sugar_g: 3,
        protein_g: 18,
        serving_size_g: 100,
        potassium_mg: 0
    },
    {
        name: 'bierkase',
        calories: 340,
        fat_total_g: 28,
        fat_saturated_g: 17,
        cholesterol_mg: 90,
        sodium_mg: 800,
        carbohydrates_total_g: 1,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 23,
        serving_size_g: 100,
        potassium_mg: 0
    },
    {
        name: 'bierschinken',
        calories: 138,
        fat_total_g: 9,
        fat_saturated_g: 3,
        cholesterol_mg: 41,
        sodium_mg: 1290,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 14,
        serving_size_g: 100,
        potassium_mg: 0
    },
    {
        name: 'bierwurst',
        calories: 232,
        fat_total_g: 18,
        fat_saturated_g: 7,
        cholesterol_mg: 62,
        sodium_mg: 900,
        carbohydrates_total_g: 2,
        fiber_g: 0,
        sugar_g: 1,
        protein_g: 15,
        serving_size_g: 100,
        potassium_mg: 0
    },
    {
        name: 'bife de costilla',
        protein_g: 22.6,
        fat_total_g: 29.1,
        fat_saturated_g: 11.3,
        carbohydrates_total_g: 0,
        calories: 358,
        cholesterol_mg: 84,
        sodium_mg: 67,
        potassium_mg: 407,
        fiber_g: 0,
        sugar_g: 0,
        serving_size_g: 100
    },
    {
        name: 'bigeye tuna',
        protein_g: 24,
        fat_total_g: 15,
        fat_saturated_g: 3.8,
        carbohydrates_total_g: 0,
        calories: 184,
        cholesterol_mg: 48,
        sodium_mg: 55,
        potassium_mg: 342,
        fiber_g: 0,
        sugar_g: 0,
        serving_size_g: 100
    },
    {
        name: 'bignay',
        protein_g: 1,
        fat_total_g: 0.5,
        fat_saturated_g: 0.1,
        carbohydrates_total_g: 12,
        calories: 49,
        cholesterol_mg: 0,
        sodium_mg: 4,
        potassium_mg: 86,
        fiber_g: 4,
        sugar_g: 0,
        serving_size_g: 100
    },
    {
        name: 'bigoli',
        protein_g: 8,
        fat_total_g: 1.5,
        fat_saturated_g: 0.3,
        carbohydrates_total_g: 75,
        calories: 353,
        cholesterol_mg: 29,
        sodium_mg: 0,
        potassium_mg: 70,
        fiber_g: 3,
        sugar_g: 0,
        serving_size_g: 100
    },
    {
        name: 'bilberry',
        protein_g: 0.7,
        fat_total_g: 0.4,
        fat_saturated_g: 0,
        carbohydrates_total_g: 14.5,
        calories: 60,
        cholesterol_mg: 0,
        sodium_mg: 7,
        potassium_mg: 85,
        fiber_g: 2.4,
        sugar_g: 7.7,
        serving_size_g: 100
    },
    {
        name: 'bilimbi',
        protein_g: 1.5,
        fat_total_g: 0.6,
        fat_saturated_g: 0.2,
        carbohydrates_total_g: 4.3,
        calories: 22,
        cholesterol_mg: 0,
        sodium_mg: 1,
        potassium_mg: 312,
        fiber_g: 2.3,
        sugar_g: 1.4,
        serving_size_g: 100
    },
    {
        name: 'biroldo',
        protein_g: 26.5,
        fat_total_g: 30.4,
        fat_saturated_g: 11.8,
        carbohydrates_total_g: 0,
        calories: 384,
        cholesterol_mg: 132,
        sodium_mg: 1100,
        potassium_mg: 380,
        fiber_g: 0,
        sugar_g: 0,
        serving_size_g: 100
    },
    {
        name: 'bitter gourd',
        calories: 17,
        fat_total_g: 0.2,
        fat_saturated_g: 0.1,
        cholesterol_mg: 0,
        sodium_mg: 1,
        carbohydrates_total_g: 3.7,
        fiber_g: 2.6,
        sugar_g: 1.2,
        protein_g: 1,
        potassium_mg: 319,
        serving_size_g: 100,
    },
    {
        name: 'black cherry',
        calories: 63,
        fat_total_g: 0.3,
        fat_saturated_g: 0,
        cholesterol_mg: 0,
        sodium_mg: 0,
        carbohydrates_total_g: 16,
        fiber_g: 2.1,
        sugar_g: 13.8,
        protein_g: 1.1,
        potassium_mg: 173,
        serving_size_g: 100,
    },
    {
        name: 'black cod',
        calories: 206,
        fat_total_g: 13.4,
        fat_saturated_g: 3.1,
        cholesterol_mg: 60,
        sodium_mg: 70,
        carbohydrates_total_g: 0,
        fiber_g: 0,
        sugar_g: 0,
        protein_g: 20.8,
        potassium_mg: 480,
        serving_size_g: 100,
    },
]