// const searchController = require('../DL/controller/searchController')
const axios = require("axios");

require("dotenv").config();
const NINJA_API_KEY = process.env.NINJA_API_KEY
// console.log(NINJA_API_KEY)

const PostNutrition = require('../DL/models/nutritionModel')

const ingredients = [
    `absinthe`,
    `abalone`,
    `abbaye de belloc`,
    `abbaye de citeaux`,
    `abbaye du mont des cats`,
    `abertam`,
    `abiu`,
    `abondance`,
    `absolut`,
    `aburana`,
    `açaí`,
    `acapella`,
    `acém`,
    `acerola`,
    `ackawi`,
    `ackee`,
    `acorn squash`,
    `acorn`,
    `adelost`,
    `adzuki beans`,
    `affidelice au chablis`,
    `african cherry orange`,
    `afuega'l pitu`,
    `agave nectar`,
    `aging salumi`,
    `ahipa`,
    `ahle wurst`,
    `airag`,
    `airedale`,
    `aisy cendre`,
    `ajowan`,
    `akebi`,
    `alaminos longganisa`,
    `pollock`,
    `salmon`,
    `albacore tuna`,
    `albariño`,
    `alcatra`,
    `alcohol`,
    `alfalfa sprouts`,
    `alfalfa`,
    `alheira`,
    `allgauer emmentaler`,
    `emmentaler`,
    `alligator apple`,
    `alligator`,
    `allspice`,
    `almond butter`,
    `almond flour`,
    `almond milk`,
    `almond yogurt`,
    `almonds`,
    `alverca`,
    `amaranth`,
    `amaretto`,
    `amazon grape`,
    `ambarella`,
    `ambert`,
    `amchur`,
    `american cheese`,
    `american elderberry`,
    `american ground nut`,
    `american groundnut`,
    `american mayapple`,
    `ami du chambertin`,
    `ananas`,
    `anchovies`,
    `andouille`,
    `andouillette`,
    `androlla`,
    `anejo enchilado`,
    `anelli`,
    `angelica`,
    `anglerfish`,
    `angostura bitters`,
    `anise`,
    `aniseed`,
    `annatto`,
    `anneau du vic-bilh`,
    `anthoriro`,
    `aonori`,
    `aperol spritz`,
    `aperol`,
    `appenzell`,
    `apple butter`,
    `apples`,
    `apricot jam`,
    `apricots`,
    `arabiki`,
    `aragon`,
    `araza`,
    `arborio rice`,
    `ardi gasna`,
    `ardrahan`,
    `arhat`,
    `armenian string`,
    `arracacha`,
    `artichoke`,
    `artichokes`,
    `arugula`,
    `asadero`,
    `asado de tira`,
    `asado`,
    `asafoetida`,
    `ash gourd`,
    `asiago cheese`,
    `asiago`,
    `asparagus`,
    `atemoya`,
    `aubergine`,
    `aubergines`,
    `aubisque pyrenees`,
    `autun`,
    `avaxtskyr`,
    `avocado oil`,
    `avocados`,
    `azaruja sausage`,
    `azuki bean`,
    `azuki beans`,
    `babaco`,
    `babic`,
    `baby swiss`,
    `babybel`,
    `bacardi`,
    `bacon`,
    `badderlocks`,
    `bael`,
    `bagels`,
    `baguette`,
    `baguio longganisa`,
    `baijiu`,
    `baileys`,
    `bakers`,
    `baladi`,
    `balaton`,
    `balkenbrij`,
    `bambara beans`,
    `bamboo shoot`,
    `banana blossom`,
    `banana squash`,
    `bananas`,
    `banat sausage`,
    `bandal`,
    `banon`,
    `barbadine`,
    `barbados cherry`,
    `barbera`,
    `barberry`,
    `barely`,
    `barley grass`,
    `barley`,
    `barnacles`,
    `barracuda`,
    `barry's bay cheddar`,
    `basa`,
    `basil`,
    `basing`,
    `basket cheese`,
    `basmati rice`,
    `bass`,
    `bath cheese`,
    `battered sausage`,
    `bavarian bergkase`,
    `bavette`,
    `bay leaf`,
    `bay leaves`,
    `bay scallop`,
    `bayberry`,
    `baylough`,
    `beach plum`,
    `bean sprouts`,
    `beans`,
    `bearberry`,
    `beaufort`,
    `beauvoorde`,
    `bee balm`,
    `beech nut`,
    `beechnut`,
    `beef sausage`,
    `beef tallow`,
    `beef`,
    `beenleigh blue`,
    `beer cheese`,
    `beer`,
    `beet greens`,
    `beet`,
    `beetroot`,
    `beets`,
    `bel paese`,
    `bell pepper`,
    `bell peppers`,
    `bellini`,
    `belutak`,
    `bergader`,
    `bergamot`,
    `bergere bleue`,
    `berkswell`,
    `berry`,
    `betel nut`,
    `betel`,
    `bethmale des pyrénées`,
    `bethmale of the pyrenees`,
    `beutelwurst`,
    `beyaz peynir`,
    `bierkase`,
    `bierschinken`,
    `bierwurst`,
    `bife de costilla`,
    `bigeye tuna`,
    `bignay`,
    `bigoli`,
    `bilberry`,
    `bilimbi`,
    `biroldo`,
    `biryani`,
    `bishop kennedy`,
    `bishops weed`,
    `bison`,
    `bitter gourd`,
    `bitter melon`,
    `bitterleaf`,
    `black apple`,
    `black beans`,
    `black cherry`,
    `black cod`,
    `black cumin`,
    `black lime`,
    `black mulberry`,
    `black mustard`,
    `black pepper`,
    `black pudding`,
    `black raspberry`,
    `black rice`,
    `black sapote`,
    `blackberries`,
    `blackberry jam`,
    `blackberry`,
    `blackcurrants`,
    `blackeyed peas`,
    `blarney`,
    `bleu d'auvergne`,
    `bleu de gex`,
    `bleu de laqueuille`,
    `bleu de septmoncel`,
    `bleu de termignon alpage`,
    `bleu des causses`,
    `blodpølse`,
    `blóðpylsa`,
    `bloedworst`,
    `blood orange`,
    `blood sausage`,
    `bloody mary`,
    `blue castello`,
    `blue cheese`,
    `blue lagoon`,
    `blue of termignon`,
    `blue rathgore`,
    `blue stilton`,
    `blue tongue`,
    `blue`,
    `blueberries`,
    `blueberry jam`,
    `bluefin tuna`,
    `bluefish`,
    `blunze`,
    `blutwurst`,
    `boar`,
    `boccoli`,
    `bocconcini`,
    `bockwurst`,
    `boeren leidenkaas`,
    `boerewors`,
    `boilermaker`,
    `bok choy`,
    `bola de lomo`,
    `boldo`,
    `bologna sausage`,
    `bolwarra`,
    `bombay duck`,
    `bonchester`,
    `bonito`,
    `borage greens`,
    `borage`,
    `bordeaux`,
    `borlotti beans`,
    `bosworth`,
    `botillo`,
    `bottle gourd`,
    `boudin blanc de rethel`,
    `boudin`,
    `bougon`,
    `boule du roves`,
    `boulette d'avesnes`,
    `bourbon`,
    `boursault`,
    `boursin`,
    `bouyssou`,
    `boysenberries`,
    `boysenberry`,
    `bra`,
    `braadworst`,
    `braai wors`,
    `bramble`,
    `brandy`,
    `bratwurst`,
    `braudostur`,
    `braughing sausage`,
    `braunschweiger`,
    `brazil nut`,
    `brazil nuts`,
    `brazil`,
    `bread flour`,
    `bread`,
    `breadfruit`,
    `breadnut`,
    `breakfast sausage`,
    `bream`,
    `brebis du lavort`,
    `brebis du lochois`,
    `brebis du puyfaucon`,
    `bregenwurst`,
    `bresse bleu`,
    `brick`,
    `brie cheese`,
    `brie`,
    `brill`,
    `brillat-savarin`,
    `brin d'amour`,
    `brin`,
    `brinjal`,
    `brinza`,
    `briquette de brebis`,
    `briquette du forez`,
    `brisket`,
    `broad beans`,
    `broadleaf arrowhead`,
    `broadleaf bramble`,
    `broccio demi-affine`,
    `broccio`,
    `broccoflower`,
    `broccoli rabe`,
    `broccoli`,
    `brousse du rove`,
    `brown lentils`,
    `brown rice syrup`,
    `brown rice`,
    `brown sugar`,
    `bruder basil`,
    `brühwurst`,
    `brussel sprout`,
    `brusselae kaas`,
    `brussels sprouts`,
    `bryndza`,
    `bucatini`,
    `buchette d'anjou`,
    `buckwheat`,
    `buddha’s hand fruit`,
    `buddha's hand`,
    `buffalo`,
    `buffaloberry`,
    `bulgur`,
    `bulls blood`,
    `bunnings sausage`,
    `burbot`,
    `burdekin plum`,
    `burdock`,
    `burger`,
    `burgos`,
    `burgundy`,
    `burmese grape`,
    `burrata`,
    `bush tomato`,
    `busiate`,
    `butifarra soledeñas`,
    `butifarra`,
    `butte`,
    `butter bean`,
    `butter beans`,
    `butter`,
    `buttercup squash`,
    `butterfly tree`,
    `butterhead lettuce`,
    `butterkase`,
    `butternut pumpkin`,
    `butternut squash`,
    `buttery nipple`,
    `button mushrooms`,
    `button`,
    `buxton blue`,
    `cabanatuan longganisa`,
    `cabbage`,
    `cabecou`,
    `cabernet sauvignon`,
    `cabernet`,
    `caboc`,
    `cabrales`,
    `cacao`,
    `cachaille`,
    `caciocavallo`,
    `caciotta`,
    `cactus pear`,
    `caerphilly`,
    `caigua`,
    `caimito`,
    `cairnsmore`,
    `cajamanga`,
    `cajna`,
    `cake flour`,
    `calabashtree`,
    `calabrese`,
    `calamarata`,
    `calamus`,
    `calenzana`,
    `calumpit longganisa`,
    `camas`,
    `cambazola`,
    `camembert cheese`,
    `camembert`,
    `camomile`,
    `campanelle or torchio`,
    `campari`,
    `camucamu`,
    `canadian cheddar`,
    `canary melon`,
    `candlenut`,
    `cane sugar`,
    `cane syrup`,
    `canestrato`,
    `canistel`,
    `canna`,
    `cannellini beans`,
    `canola oil`,
    `cantal`,
    `cantaloupes`,
    `cape gooseberry`,
    `capellini`,
    `capers`,
    `cap'n crunch`,
    `cappelli da chef`,
    `caprice des dieux`,
    `capricorn goat`,
    `capriole banon`,
    `capsicum`,
    `captain morgan`,
    `carambola`,
    `caravane`,
    `caraway`,
    `cardamom`,
    `cardon`,
    `cardoon`,
    `carnation`,
    `carob`,
    `carola`,
    `carre de l'est`,
    `carrots`,
    `casarecce`,
    `cascatelli`,
    `casciotta di urbino`,
    `cashel blue`,
    `cashew ice cream`,
    `cashew milk`,
    `cashew yogurt`,
    `cashews`,
    `cassava`,
    `cassia`,
    `castellane`,
    `castelleno`,
    `castelmagno`,
    `castelo branco`,
    `castigliano`,
    `catfish`,
    `cathelain`,
    `catsear`,
    `cauliflower`,
    `cavatappi`,
    `cavatelli`,
    `caviar lime`,
    `caviar`,
    `cayenne pepper`,
    `ceci beans`,
    `cedar bay cherry`,
    `celeriac`,
    `celery leaves`,
    `celery`,
    `celtic promise`,
    `celtic sea salt`,
    `celtuce`,
    `cempedak`,
    `cencioni`,
    `cendre d'olivet`,
    `cephalopods`,
    `cereal`,
    `cerney`,
    `cervela`,
    `cervelas de lyon`,
    `cervelat`,
    `cervelatwurst`,
    `cervellata`,
    `češnovka`,
    `ceylon gooseberry`,
    `cha com`,
    `cha lua`,
    `cha`,
    `chabichou du poitou`,
    `chabichou`,
    `chabis de gatine`,
    `chamomile`,
    `champagne cocktail`,
    `champagne melon`,
    `champagne`,
    `chana dal`,
    `chaource`,
    `char`,
    `chard`,
    `chardonnay`,
    `charolais`,
    `chartreuse`,
    `chaudin`,
    `chaumes`,
    `chaya`,
    `chayote`,
    `che`,
    `cheddar cheese curds`,
    `cheddar cheese sauce`,
    `cheddar cheese`,
    `cheddar clothbound`,
    `cheddar jack`,
    `cheddar spread`,
    `cheddar`,
    `cheerios`,
    `cheese`,
    `chempedak`,
    `chenet`,
    `chenin blanc`,
    `cherimoya`,
    `cherries`,
    `cherry preserves`,
    `cherry tomato`,
    `cherry`,
    `chervil`,
    `cheshire`,
    `chestnuts`,
    `chevres`,
    `chevrotin des aravis`,
    `chia seeds`,
    `chianti`,
    `chick pea`,
    `chicken eggs`,
    `chicken longganisa`,
    `chicken`,
    `chickpea flour`,
    `chickpeas`,
    `chickweed`,
    `chico fruit`,
    `chicory`,
    `chifferi`,
    `chile pepper`,
    `chile varieties`,
    `chilean sea bass`,
    `chili pepper`,
    `chili powder`,
    `chili`,
    `chilies`,
    `chilli powder`,
    `chinchulín`,
    `chinese artichoke`,
    `chinese bayberry`,
    `chinese cabbage`,
    `chinese chives`,
    `chinese hibiscus`,
    `chinese mallow`,
    `chinese mulberry`,
    `chinese okra`,
    `chipolata`,
    `chips`,
    `chistorra`,
    `chives`,
    `chocolate milk`,
    `chocolate pudding fruit`,
    `chocolate syrup`,
    `chocolate`,
    `chokeberry`,
    `chontaleno`,
    `chorizo de bilbao`,
    `chorizo de cebu`,
    `chorizo de macao`,
    `chorizo negrense`,
    `chorizo`,
    `chouriço doce`,
    `chouriço`,
    `choy sum`,
    `chrysanthemum leaves`,
    `chrysanthemum`,
    `chuck`,
    `chunchullo`,
    `ciauscolo`,
    `ciavar`,
    `cicioneddos`,
    `cider`,
    `cilantro`,
    `cinnamon toast crunch`,
    `cinnamon`,
    `cinsault`,
    `cinzano`,
    `citron`,
    `civray`,
    `clams`,
    `clementines`,
    `cloudberry`,
    `cloves`,
    `cluster fig`,
    `cockle`,
    `coco de mer`,
    `cocoa puffs`,
    `coconut cream`,
    `coconut flour`,
    `coconut ice cream`,
    `coconut milk`,
    `coconut nectar`,
    `coconut oil`,
    `coconut sugar`,
    `coconut water`,
    `coconut yogurt`,
    `coconut`,
    `cocoplum`,
    `cod`,
    `coeur de camembert au calvados`,
    `coeur de chevre`,
    `coffee`,
    `cognac`,
    `cointreau`,
    `cojack`,
    `colby`,
    `colby-jack`,
    `cold pack`,
    `cold pressed olive`,
    `colita de cuadril`,
    `collard greens`,
    `collards`,
    `common apple-berry`,
    `common beans`,
    `common dandelion`,
    `sage`,
    `common violet`,
    `comte`,
    `conch`,
    `conchiglie`,
    `conkerberry`,
    `contrafilé`,
    `cooked fruits`,
    `cooked meats`,
    `cooked vegetables`,
    `coolea`,
    `cooleney`,
    `coquetdale`,
    `coral lettuce`,
    `coriander`,
    `corleggy`,
    `corms`,
    `corn flakes`,
    `corn kernel`,
    `corn nuts`,
    `corn oil`,
    `corn syrup`,
    `corn`,
    `cornelian cherry`,
    `cornflower`,
    `cornish pepper`,
    `cornmeal`,
    `corzetti`,
    `cos lettuce`,
    `cosmopolitan`,
    `cotechino modena`,
    `cotechino`,
    `cotherstone`,
    `cotija`,
    `cottage cheese`,
    `cougar gold`,
    `coulommiers`,
    `courgette`,
    `couscous`,
    `coverdale`,
    `cowpeas`,
    `coxão duro`,
    `coxão mole`,
    `crab apple`,
    `crab`,
    `crabapple`,
    `crabs`,
    `crackers`,
    `cranberries`,
    `craw`,
    `cray fish`,
    `crayeux de roncq`,
    `cream cheese`,
    `cream havarti`,
    `crema agria`,
    `crema mexicana`,
    `creme de cassis`,
    `creme de menthe`,
    `creme fraiche`,
    `cremini mushrooms`,
    `crescenza`,
    `cress`,
    `creste di galli`,
    `croghan`,
    `croissants`,
    `crottin de chavignol`,
    `crowberry`,
    `crowdie`,
    `crowley`,
    `crustaceans`,
    `csabai`,
    `cuadril`,
    `cuajada`,
    `cubeb`,
    `cucumbers`,
    `cucurbits`,
    `cudpahnut`,
    `cudrang`,
    `cudrania`,
    `cumberland sausage`,
    `cumin`,
    `cupim`,
    `cupuacu`,
    `curd`,
    `cure nantais`,
    `currant`,
    `curry`,
    `curworthy`,
    `custard apple`,
    `custard squash`,
    `cuttlefish`,
    `pecorino`,
    `cymbopogon`,
    `cypress grove chevre`,
    `daikon`,
    `daiquiri`,
    `daisy`,
    `damson`,
    `danablu`,
    `danbo`,
    `dandelion greens`,
    `dandelion`,
    `danish fontina`,
    `daralagjazsky`,
    `date palm`,
    `date sugar`,
    `date-plum`,
    `dates`,
    `dauphin`,
    `davidson's plum`,
    `daylily`,
    `debrecener`,
    `delicata`,
    `delice des fiouves`,
    `denhany dorset drum`,
    `derby`,
    `desert fig`,
    `desert lime`,
    `dessertnyj belyj`,
    `devon blue`,
    `devon garland`,
    `devon`,
    `dewberry`,
    `dill pickle`,
    `dill`,
    `diot`,
    `disaronno`,
    `dogfish`,
    `dogtooth tuna`,
    `doh snam`,
    `doi`,
    `doktorskaya kolbasa`,
    `dolcelatte`,
    `dolichos bean`,
    `donuts`,
    `doolin`,
    `doppelrhamstufel`,
    `dorade`,
    `dorset blue vinney`,
    `dosa`,
    `doubah`,
    `double gloucester`,
    `double worcester`,
    `dragon fruit`,
    `dragon sausage`,
    `dragonfruit`,
    `dragonrfruit`,
    `dreux a la feuille`,
    `dried apples`,
    `dried apricots`,
    `dried bananas`,
    `dried beans`,
    `dried cherries`,
    `dried coconut`,
    `dried cranberries`,
    `dried figs`,
    `dried fruit`,
    `dried fruits`,
    `dried garlic`,
    `dried herbs`,
    `dried lentils`,
    `dried mango`,
    `dried mangoes`,
    `dried meats`,
    `dried mushrooms`,
    `dried noodles`,
    `dried onions`,
    `dried papayas`,
    `dried peas`,
    `dried peppers`,
    `dried plum`,
    `dried prunes`,
    `dried seaweed`,
    `dried spices`,
    `dried tomatoes`,
    `drisheen`,
    `droewors`,
    `drumstick`,
    `dry jack`,
    `dry plums`,
    `duck eggs`,
    `duck`,
    `duddleswell`,
    `dudhi`,
    `dulse`,
    `dunbarra`,
    `dunlop`,
    `dunsyre blue`,
    `durain`,
    `durian`,
    `duroblando`,
    `durrus`,
    `dutch mimolette`,
    `earthnut pea`,
    `eastern may hawthorn`,
    `edam`,
    `edamame`,
    `eddoe`,
    `edelpilz`,
    `eel`,
    `egg fruit`,
    `egg`,
    `eggfruit`,
    `eggplant`,
    `eggs`,
    `einkorn`,
    `elder`,
    `elderberries`,
    `elderberry`,
    `elephant apple`,
    `elephant foot yam`,
    `elephant garlic`,
    `elim wors`,
    `elk`,
    `emblic`,
    `embutido`,
    `emental grand cru`,
    `emlett`,
    `emmental`,
    `emmer`,
    `emu apple`,
    `emu`,
    `endive`,
    `energy drinks`,
    `enoki mushrooms`,
    `ensete`,
    `entawak`,
    `entraña`,
    `epazote`,
    `epoisses de bourgogne`,
    `erythritol`,
    `esbareich`,
    `escarole`,
    `esrom`,
    `etorki`,
    `etrog`,
    `evansdale farmhouse brie`,
    `evora de l'alentejo`,
    `exmoor blue`,
    `explorateur`,
    `extrawurst`,
    `fagioloni`,
    `fainelle`,
    `falda`,
    `falsa`,
    `falukorv`,
    `farfalle`,
    `farinheira`,
    `farmer`,
    `farro`,
    `fat hen`,
    `fava beans`,
    `fava greens`,
    `fazzoletti`,
    `feather blade`,
    `fedelini`,
    `feijoa`,
    `fennel seeds`,
    `fennel`,
    `fenugreek greens`,
    `fenugreek`,
    `ferrazzuoli`,
    `festoni`,
    `feta cheese`,
    `feta`,
    `fettuccine`,
    `fibrous satinash`,
    `fiddlehead`,
    `fiddleheads`,
    `fig preserves`,
    `figs`,
    `figue`,
    `fiji longan`,
    `filé mignon`,
    `fileja`,
    `filetta`,
    `fillet`,
    `fin-de-siecle`,
    `finger lime`,
    `finlandia swiss`,
    `finn`,
    `fiore sardo`,
    `fiorentine`,
    `fiori`,
    `fish longganisa`,
    `fish sausage`,
    `fish`,
    `flaming dr. pepper`,
    `flank`,
    `fläskkorv`,
    `flax seeds`,
    `flax`,
    `flaxseed oil`,
    `fleischwurst`,
    `fleur du maquis`,
    `flor de guia`,
    `florence fennel`,
    `flounder`,
    `flour`,
    `flower marie`,
    `flowering cabbage`,
    `fluted pumpkin`,
    `foglie d'ulivo`,
    `folded cheese with mint`,
    `folded`,
    `fondant de brebis`,
    `fontainebleau`,
    `fontal`,
    `fontina val d'aosta`,
    `fontina`,
    `fore rib`,
    `formaggio di capra`,
    `fougerus`,
    `four herb gouda`,
    `four horsemen`,
    `fourme d' ambert`,
    `fourme de haute loire`,
    `fourme de montbrison`,
    `fox nuts`,
    `fraldinha`,
    `frangelico`,
    `frankfurter rindswurst`,
    `frankfurter würstchen`,
    `frankfurter`,
    `french 75`,
    `french bean`,
    `french fries`,
    `french lentils`,
    `french marigold`,
    `fresh jack`,
    `fresh mozzarella`,
    `fresh ricotta`,
    `fresh truffles`,
    `fribourgeois`,
    `friesekaas`,
    `friesian`,
    `friesla`,
    `frikandel`,
    `frinault`,
    `frisee`,
    `frizzmo`,
    `fromage a raclette`,
    `fromage corse`,
    `fromage de montagne de savoie`,
    `fromage frais`,
    `froot loops`,
    `frosted flakes`,
    `fruit cream cheese`,
    `fruit infused water`,
    `fruit syrup`,
    `fruit`,
    `frying cheese`,
    `fuet`,
    `fugu`,
    `fusilli bucati`,
    `fusilli`,
    `fuyu persimmon`,
    `fynbo`,
    `gabriel`,
    `galangal`,
    `galendar`,
    `galette du paludier`,
    `galette lyonnaise`,
    `galia melon`,
    `galia`,
    `galloway goat's milk gems`,
    `gammelost`,
    `gandaria`,
    `gaperon a l'ail`,
    `garbanzo beans`,
    `garbanzos`,
    `garden nasturtium`,
    `garden pea`,
    `garden rocket`,
    `garganelli`,
    `garlic powder`,
    `garlic`,
    `garnacha`,
    `garrotxa`,
    `gastanberra`,
    `geitost`,
    `gelbwurst`,
    `gem squash`,
    `gemelli`,
    `genip`,
    `genipap`,
    `genoa salami`,
    `geranium`,
    `gewürztraminer`,
    `gherkin`,
    `giant granadilla`,
    `gin and tonic`,
    `gin fizz`,
    `gin`,
    `ginger`,
    `gippsland blue`,
    `gjetost`,
    `glamorgan sausage`,
    `globe artichokes`,
    `gloucester sausage`,
    `gloucester`,
    `gnocchi`,
    `goan sausage`,
    `goat cheese`,
    `goat`,
    `gobo`,
    `goetta`,
    `goji berry`,
    `golden apple`,
    `golden cross`,
    `golden kiwi`,
    `golden nugget squash`,
    `golden samphire`,
    `golden syrup`,
    `gomiti`,
    `gonjura`,
    `good king henry`,
    `goose eggs`,
    `gooseberries`,
    `gooseberry`,
    `gorgonzola`,
    `gornyaltajski`,
    `gospel green`,
    `gouda cheese`,
    `gouda`,
    `goumi`,
    `gourds`,
    `goutu`,
    `gowrie`,
    `grabetto`,
    `grabouw wors`,
    `graddost`,
    `grafton village cheddar`,
    `grana padano`,
    `grana`,
    `grand marnier`,
    `grand vatel`,
    `granola`,
    `grape`,
    `grapefruits`,
    `grape-nuts`,
    `grapes`,
    `grapeseed oil`,
    `grapple`,
    `grataron d' areches`,
    `gratte-paille`,
    `graviera`,
    `green apple`,
    `green beans`,
    `green gooseberry`,
    `green grapes`,
    `green lentils`,
    `green onion`,
    `green peas`,
    `green tea shot`,
    `greenbeans`,
    `greengage plum`,
    `greengage`,
    `greens`,
    `grenache`,
    `grenadilla`,
    `greuilh`,
    `greve`,
    `grewia asiatica`,
    `grilled chicken`,
    `grillpølse`,
    `grillworst`,
    `gris de lille`,
    `grouper`,
    `gruner veltliner`,
    `gruyere`,
    `guagua longganisa`,
    `guanabana`,
    `guar`,
    `guarana`,
    `guava`,
    `guavaberry`,
    `guavas`,
    `guavasteen`,
    `gubbeen`,
    `guerbigny`,
    `gyulai`,
    `habanero`,
    `habenero pepper`,
    `hackberry`,
    `haddock`,
    `haggis`,
    `hake`,
    `hala fruit`,
    `halibut`,
    `halloumi`,
    `hamburg parsley`,
    `harbourne blue`,
    `hardy kiwi`,
    `haricot beans`,
    `havarti cheese`,
    `havarti`,
    `hawthorn berry`,
    `hawthorn`,
    `hazelnut oil`,
    `hazelnuts`,
    `heart's ease`,
    `heidi gruyere`,
    `hemp milk`,
    `hemp seeds`,
    `hemp`,
    `herbal tea`,
    `herbs`,
    `hereford hop`,
    `herrgardsost`,
    `herring`,
    `herriot farmhouse`,
    `herve`,
    `hijiki`,
    `hipi iti`,
    `hog maw`,
    `hog plum`,
    `hog's pudding`,
    `hoja santa`,
    `honey nut cheerios`,
    `honey`,
    `honeyberries`,
    `honeyberry`,
    `honeycrisp apple`,
    `honeydew melons`,
    `honeydew`,
    `honeysuckle`,
    `horned melon`,
    `horse gram`,
    `horseradish`,
    `hot chocolate`,
    `hot dog`,
    `hot link`,
    `hotdog`,
    `hot-house cucumber`,
    `hubbard squash`,
    `hubbardston blue cow`,
    `huckleberry`,
    `huito`,
    `humboldt fog`,
    `hummus`,
    `hungarian sausages`,
    `hurka`,
    `hushallsost`,
    `husk cherry`,
    `hyacinth beans`,
    `hyssop`,
    `iberico`,
    `ice apple`,
    `ice cream`,
    `ice plant`,
    `iceberg lettuce`,
    `iced tea`,
    `idaho goatster`,
    `idiazabal`,
    `ikura`,
    `il boschetto al tartufo`,
    `ile d'yeu`,
    `ilish`,
    `illawarra plum`,
    `inca berry`,
    `indian almond`,
    `indian cress`,
    `indian fig`,
    `indian jujube`,
    `indian pea`,
    `indian prune`,
    `indian strawberry`,
    `irish car bomb`,
    `irish coffee`,
    `ironbark pumpkin`,
    `isle of mull`,
    `isterband`,
    `ita palm`,
    `italian red onion`,
    `italian sausage`,
    `ivy gourd`,
    `jaboticaba`,
    `jack beans`,
    `jack daniels`,
    `jackfruit`,
    `jagdwurst`,
    `jägerbomb`,
    `jägermeister`,
    `jagua`,
    `jalapeno pepper`,
    `jalapeño`,
    `jamaica cherry`,
    `jamaican sorrel`,
    `jambu`,
    `jambul`,
    `japanese amberjack`,
    `japanese bayberry`,
    `japanese bunching onions`,
    `japanese butterfish`,
    `japanese honeysuckle`,
    `japanese plum`,
    `japanese pumpkin`,
    `japanese raisin`,
    `jarlsberg`,
    `jasmine rice`,
    `jatoba`,
    `jausenwurst`,
    `jelito`,
    `jello shots`,
    `jenipapo`,
    `jermi tortes`,
    `jerusalem artichoke`,
    `jerusalem artichokes`,
    `jibneh arabieh`,
    `jicama`,
    `jim beam`,
    `jindi brie`,
    `jocote`,
    `john dory`,
    `johnnie walker`,
    `jostaberry`,
    `jubilee blue`,
    `juice`,
    `jujube`,
    `june plum`,
    `juniper berry`,
    `juniper`,
    `juustoleipa`,
    `kabanos`,
    `kabosu`,
    `kadchgall`,
    `kaffir lime`,
    `kahikatea`,
    `kahlua`,
    `kai-lan`,
    `kakadu lime`,
    `kakadu plum`,
    `kale`,
    `kamut`,
    `kandis fruit`,
    `kanga bangas`,
    `karkalla`,
    `karuka`,
    `käsekrainer`,
    `kaseri`,
    `kashta`,
    `kaszanka`,
    `kazunoko`,
    `kefalotyri`,
    `kenafa`,
    `keppel fruit`,
    `kernhem`,
    `kervella affine`,
    `key lime`,
    `kidney beans`,
    `kiełbasa biała`,
    `kiełbasa jałowcowa`,
    `kiełbasa myśliwska`,
    `kiełbasa wędzona`,
    `kielbasa`,
    `kikorangi`,
    `kimchee`,
    `king island cape wickham brie`,
    `king river gold`,
    `kir royale`,
    `kishka`,
    `kiwano`,
    `kiwi fruit`,
    `kiwi`,
    `kiwiberries`,
    `kiwifruit`,
    `klosterkaese`,
    `knackwurst`,
    `knakworst`,
    `knipp`,
    `knoblewurst`,
    `knockalara`,
    `knockwurst`,
    `kohlrabi`,
    `kohlwurst`,
    `kokum`,
    `kola nut`,
    `komatsuna`,
    `kombu`,
    `kombucha`,
    `konjac`,
    `kosher pickle`,
    `krakowska`,
    `krispy`,
    `krvavnička`,
    `kugelkase`,
    `kuka`,
    `kulen`,
    `kumquat`,
    `kundong`,
    `kupati`,
    `kurobuta`,
    `kurrat`,
    `kutjera`,
    `la taupiniere`,
    `la vache qui rit`,
    `lablab`,
    `lady apple`,
    `lagane`,
    `lagarto`,
    `lagos bologi`,
    `laguiole`,
    `lairobell`,
    `lajta`,
    `lamb`,
    `lamprey`,
    `lanark blue`,
    `lancashire`,
    `land cress`,
    `landjäger`,
    `langres`,
    `langsat`,
    `lanterne`,
    `lanzones`,
    `lao sausage`,
    `lạp xưởng`,
    `lappi`,
    `lapsi`,
    `lard`,
    `laruns`,
    `lasagna`,
    `lasagnette`,
    `lasagnotte`,
    `lavender`,
    `laver`,
    `l'aveyronnais`,
    `lavistown`,
    `le brin`,
    `le fium orbo`,
    `le lacandou`,
    `le roule`,
    `leafield`,
    `lebanese cucumber`,
    `lebanon bologna`,
    `lebbene`,
    `leberkäse`,
    `leberwurst`,
    `l'ecir de l'aubrac`,
    `leeks`,
    `leerdammer`,
    `legume`,
    `legumes`,
    `leicester`,
    `lekor`,
    `lemon aspen`,
    `lemon balm`,
    `lemon grass`,
    `lemon myrtle`,
    `lemon plum`,
    `lemon verbena`,
    `lemon`,
    `lemonade`,
    `lemongrass`,
    `lemons`,
    `lentils`,
    `lettuce`,
    `leucaena`,
    `leyden`,
    `licorice`,
    `likëngë`,
    `lilac`,
    `lillipilli`,
    `lilly pilly`,
    `lima beans`,
    `limburger`,
    `limes`,
    `lincolnshire poacher`,
    `lincolnshire sausage`,
    `linden`,
    `lingcod`,
    `lingonberry`,
    `lingot saint bousquet d'orb`,
    `linguica`,
    `linguine`,
    `liptauer`,
    `liptovská saláma`,
    `liquid cocaine`,
    `little rydings`,
    `livarot`,
    `liverwurst`,
    `lizard’s tail`,
    `llanboidy`,
    `llanglofan farmhouse`,
    `lobster`,
    `lobsters`,
    `loch arthur farmhouse`,
    `loco`,
    `loddiswell avondale`,
    `loganberry`,
    `lomo`,
    `long island iced tea`,
    `longan`,
    `longaniza de guinobatan`,
    `longaniza`,
    `longganisa`,
    `longhorn`,
    `loofah`,
    `loomi`,
    `loquat`,
    `lorighittas`,
    `lorne sausage`,
    `lotus root`,
    `lou palou`,
    `lou pevre`,
    `loukaniko`,
    `lovage`,
    `lucban longganisa`,
    `lucky charms`,
    `lucuma`,
    `luffa`,
    `luganega`,
    `lukanka`,
    `lulo`,
    `lumpfish roe`,
    `lunenburg pudding`,
    `lupin beans`,
    `lychee`,
    `lychees`,
    `lyoner`,
    `lyonnais`,
    `maasdam`,
    `mabolo`,
    `macadamia nuts`,
    `macadamia`,
    `macaroni`,
    `maccheroncelli`,
    `maccheroncini di campofilone`,
    `maccheroni alla molinara`,
    `macconais`,
    `mace`,
    `mackerel`,
    `madeira`,
    `mafalde`,
    `mafaldine`,
    `magellan barberry`,
    `mahi mahi`,
    `mahlab`,
    `mahoe aged gouda`,
    `mahon`,
    `mai tai`,
    `maitake mushrooms`,
    `maize`,
    `makanek`,
    `makers mark`,
    `makrut lime`,
    `malabar chestnut`,
    `malabar gourd`,
    `malabar spinach`,
    `malay apple`,
    `malbec`,
    `malloreddus`,
    `maltagliati`,
    `malvern`,
    `mamey apple`,
    `mamey sapote`,
    `mamin chino`,
    `maminha`,
    `mamirolle`,
    `mamoncillo`,
    `manchego`,
    `manchester sausage`,
    `mandala`,
    `mandarin orange`,
    `mandarin`,
    `mandarine`,
    `mandarins`,
    `mange tout`,
    `mangelwurzel`,
    `mango`,
    `mangoes`,
    `mangos`,
    `mangosteen`,
    `mangosteens`,
    `manhattan`,
    `manila tamarind`,
    `manoao`,
    `manouri`,
    `manur`,
    `maple syrup`,
    `marang`,
    `marble cheddar`,
    `marbled cheeses`,
    `marcona almonds`,
    `maredsous`,
    `margarine`,
    `margarita`,
    `margotin`,
    `maribo`,
    `marigold`,
    `marille`,
    `marion berry`,
    `marionberry`,
    `marjoram`,
    `maroilles`,
    `marrow`,
    `martini & rossi`,
    `martini`,
    `marylebone sausage`,
    `masago`,
    `mascares`,
    `mascarpone torta`,
    `mascarpone`,
    `mashua`,
    `masoor dal`,
    `mastic`,
    `matambre`,
    `matocq`,
    `matriciani`,
    `mayapple`,
    `mayhaw`,
    `mayonnaise`,
    `maypop`,
    `maytag blue`,
    `mazzafegati`,
    `meatball`,
    `medisterpølse`,
    `medlar fruit`,
    `medlar`,
    `meira`,
    `melegueta pepper`,
    `melinjo`,
    `melokhia`,
    `melon pear`,
    `melon`,
    `menallack farmhouse`,
    `menonita`,
    `meredith blue`,
    `merguez`,
    `merlot`,
    `mesost`,
    `metton`,
    `mettwurst`,
    `metworst`,
    `meyer vintage gouda`,
    `mezcal margarita`,
    `mezcal`,
    `mezzani`,
    `mezze maniche`,
    `mezze penne`,
    `mezzi bombardoni`,
    `michelada`,
    `midori`,
    `midyim`,
    `mihalic peynir`,
    `milk`,
    `milleens`,
    `millet`,
    `mimolette`,
    `mimosa`,
    `mine-gabhar`,
    `miner’s lettuce`,
    `mini baby bells`,
    `minikin pumpkin`,
    `mint`,
    `miracle fruit`,
    `mixte`,
    `mizuna greens`,
    `mock buckthorn`,
    `mock strawberry`,
    `mojito`,
    `molasses`,
    `molbo`,
    `mollejas`,
    `mollusca`,
    `momordica fruit`,
    `monastery cheeses`,
    `monastrell`,
    `mondseer`,
    `mongongo`,
    `monguete`,
    `monk fruit sweetener`,
    `monkey apple`,
    `monkfish`,
    `monks cress.`,
    `monstera deliciosa`,
    `monstera`,
    `mont d'or lyonnais`,
    `montasio`,
    `monterey jack dry`,
    `monterey jack`,
    `moong dal`,
    `möpkenbrot`,
    `morbier cru de montagne`,
    `morbier`,
    `morcilla`,
    `morcón`,
    `morel mushrooms`,
    `morel`,
    `morinda`,
    `moronga`,
    `morrpølse`,
    `mortadella`,
    `morteau sausage`,
    `moscato`,
    `moscow mule`,
    `moth bean`,
    `moth beans`,
    `moth orchid`,
    `mothais a la feuille`,
    `mother beans`,
    `mountain pepper`,
    `mountain soursop`,
    `mourvèdre`,
    `mouse melon`,
    `mozuku`,
    `mozzarella cheese`,
    `mozzarella di bufala`,
    `mozzarella fresh`,
    `mozzarella rolls`,
    `mozzarella`,
    `muenster`,
    `muffins`,
    `mulberries`,
    `müller-thurgau`,
    `mullet`,
    `mundu`,
    `mung bean`,
    `mung beans`,
    `munster`,
    `muntries`,
    `murol`,
    `muscat`,
    `mushrooms`,
    `musk melon`,
    `muskmelon`,
    `muskmelons`,
    `mussel`,
    `mussels`,
    `must melon`,
    `mustamakkara`,
    `mustard greens`,
    `mustard seeds`,
    `mustard`,
    `mycella`,
    `myrtle`,
    `myśliwska`,
    `myzithra`,
    `naan`,
    `naboulsi`,
    `nădlac sausage`,
    `naem`,
    `nageia`,
    `nance`,
    `nannyberry`,
    `nantais`,
    `napa cabbage`,
    `naples cos`,
    `naranja`,
    `naranjilla`,
    `native cherry`,
    `native currant`,
    `native gooseberry`,
    `nautilus`,
    `navette`,
    `navy beans`,
    `nduja`,
    `nebbiolo`,
    `necks`,
    `nectarine`,
    `neem`,
    `nettles`,
    `neufchatel`,
    `new potato`,
    `new zealand spinach`,
    `newmarket sausage`,
    `nigella`,
    `niolo`,
    `noilly prat`,
    `nokkelost`,
    `noni fruit`,
    `noodles`,
    `nopal`,
    `northumberland`,
    `noumboulo`,
    `nungu`,
    `nürnberger bratwürste`,
    `nut cheese`,
    `nutmeg`,
    `nuvole`,
    `oakleaf lettuce`,
    `oat flour`,
    `oat ice cream`,
    `oat milk`,
    `oatmeal`,
    `oats`,
    `oaxaca`,
    `oca`,
    `octopus`,
    `ogonori`,
    `oil palm`,
    `ojo de bife`,
    `okra`,
    `olallieberry`,
    `old world sycomore`,
    `olde york`,
    `olive oil`,
    `olive`,
    `olives`,
    `olivet au foin`,
    `olivet bleu`,
    `olivet cendre`,
    `onion powder`,
    `onion`,
    `onions`,
    `orach`,
    `orache`,
    `orange roughy`,
    `orange`,
    `orangelo`,
    `oranges`,
    `orchid tree`,
    `orecchiette`,
    `oregano`,
    `oregon grape`,
    `orkney extra mature cheddar`,
    `orla`,
    `orris root`,
    `osage orange`,
    `oschtjepka`,
    `ossau fermier`,
    `ossau-iraty`,
    `ossenworst`,
    `oszczypek`,
    `otaheite apple`,
    `ouzo`,
    `oxford blue`,
    `oxford sausage`,
    `oxtail`,
    `oyster mushrooms`,
    `oyster plant`,
    `oyster`,
    `oysters`,
    `paccheri`,
    `pacific rudderfish`,
    `pacific saury`,
    `pacific snapper`,
    `painkiller`,
    `paio`,
    `pak-choi`,
    `palet de babligny`,
    `paleta`,
    `palm nuts`,
    `palm oil`,
    `palmetto`,
    `paloma`,
    `pampanga longganisa`,
    `pancake`,
    `pancakes`,
    `paneer`,
    `panela`,
    `pannerone`,
    `pansy`,
    `pant ys gawn`,
    `papaya`,
    `papayas`,
    `pappardelle`,
    `paprika`,
    `paracress`,
    `parmesan cheese`,
    `parmesan`,
    `parmigiano reggiano`,
    `parrotfish`,
    `parsley`,
    `parsnip`,
    `parsnips`,
    `parwal`,
    `pas de l'escalette`,
    `passatelli`,
    `passendale`,
    `passion flower`,
    `passion fruit`,
    `pasta al ceppo`,
    `pasta`,
    `pastis`,
    `pastrami`,
    `pastries`,
    `pastry flour`,
    `patagonian toothfish`,
    `pate de fromage`,
    `patefine fort`,
    `patinho`,
    `patron`,
    `pattypan squash`,
    `pave d'affinois`,
    `pave d'auge`,
    `pave de chirac`,
    `pave du berry`,
    `pawpaw`,
    `pea milk`,
    `pea`,
    `peach preserves`,
    `peach`,
    `peaches`,
    `peanut butter`,
    `peanut oil`,
    `peanuts`,
    `pear`,
    `pears`,
    `peas`,
    `pecans`,
    `pecho`,
    `pecorino in walnut leaves`,
    `pecorino romano`,
    `pecorino`,
    `peekskill pyramid`,
    `pelardon des cevennes`,
    `pelardon des corbieres`,
    `penamellera`,
    `penbryn`,
    `pencarreg`,
    `penne ricce`,
    `penne`,
    `pepper jack`,
    `pepper`,
    `peppermint`,
    `pepperoni`,
    `peppers`,
    `pequi`,
    `perail de brebis`,
    `perch`,
    `perciatelli`,
    `perennial cucumber`,
    `periwinkle`,
    `persimmons`,
    `petit morin`,
    `petit pardou`,
    `petit verdot`,
    `petite sirah`,
    `petit-suisse`,
    `pe-tsai`,
    `pewa`,
    `phalsa`,
    `physalis`,
    `picagge`,
    `picanha`,
    `picchiarelli`,
    `pici`,
    `pick`,
    `pickle`,
    `pickles`,
    `pickling onions`,
    `picodon de chevre`,
    `picos de europa`,
    `pie`,
    `pigeon pea`,
    `pigeon plum`,
    `pigface`,
    `pignut`,
    `pike`,
    `pilchard`,
    `pili nut`,
    `pili nuts`,
    `pillus`,
    `pina colada`,
    `pinconning`,
    `pine nuts`,
    `pineapple guava`,
    `pineapple sage`,
    `pineapple`,
    `pineapples`,
    `pineberry`,
    `pinkel`,
    `pinot grigio`,
    `pinot noir`,
    `pinto beans`,
    `pinuneg`,
    `piora`,
    `pipe rigate`,
    `pisco sour`,
    `pisco`,
    `pistachios`,
    `pita bread`,
    `pitaya`,
    `pithtviers au foin`,
    `pitomba`,
    `pizza`,
    `pizzoccheri`,
    `plaaswors`,
    `plantain`,
    `plateau de herve`,
    `plectranthus`,
    `pleşcoi sausage`,
    `plinia`,
    `plum preserves`,
    `plum`,
    `plumcot`,
    `plums`,
    `pluot`,
    `plymouth cheese`,
    `podhalanski`,
    `podocarpus`,
    `poha`,
    `pois doux`,
    `poivre d'ane`,
    `poke`,
    `polenta`,
    `polk`,
    `polkolbin`,
    `pollock`,
    `pomcite`,
    `pomegranate`,
    `pomegranates`,
    `pomelo`,
    `pomfret`,
    `pommecythere`,
    `pommerac`,
    `pompano`,
    `pond apple`,
    `pont l'eveque`,
    `popcorn`,
    `poppy seeds`,
    `poppyseed`,
    `pork and apple`,
    `pork and leek`,
    `pork sausage`,
    `pork`,
    `port nicholson`,
    `port wine`,
    `port`,
    `portobello mushrooms`,
    `port-salut`,
    `postel`,
    `potatiskorv`,
    `potato chips`,
    `potato`,
    `potatoes`,
    `pouligny-saint-pierre`,
    `pourly`,
    `powdered sugar`,
    `prairie turnip`,
    `prasky`,
    `prastost`,
    `prawns`,
    `pressato`,
    `pretzels`,
    `prickly pear`,
    `prince-jean`,
    `prinskorv`,
    `processed cheddar`,
    `processed foods and snacks`,
    `prosecco`,
    `provel`,
    `provolone cheese`,
    `provolone`,
    `prumnopitys`,
    `prunes`,
    `prussian asparagus`,
    `p'tit berrichon`,
    `pufferfish`,
    `pulasan`,
    `pummelo`,
    `pumpkin seeds`,
    `pumpkin`,
    `pupunha`,
    `purple apple-berry`,
    `purple bauhinia`,
    `purple mangosteen`,
    `purslane`,
    `pyengana cheddar`,
    `pyramide`,
    `qazy`,
    `quadrefiore`,
    `quail eggs`,
    `quail`,
    `quandong`,
    `quark`,
    `quartirolo lombardo`,
    `quatre-vents`,
    `quenepa`,
    `quercy petit`,
    `quesadilla cheese`,
    `queso blanco`,
    `queso de murcia`,
    `queso del montsec`,
    `queso del tietar`,
    `queso fresco`,
    `queso iberico`,
    `queso jalapeno`,
    `queso majorero`,
    `queso media luna`,
    `queso para frier`,
    `queso quesadilla`,
    `quince`,
    `quinoa seeds`,
    `quinoa`,
    `rabacal`,
    `raclette`,
    `radiatori`,
    `radicchio`,
    `radiccio`,
    `radish`,
    `radishes`,
    `ragusano`,
    `rainbow chard`,
    `rainbow trout`,
    `raisin`,
    `raisins`,
    `raki`,
    `rakia`,
    `rambutan`,
    `ramphal`,
    `rangpur`,
    `raschera`,
    `raspberries`,
    `raspberry jam`,
    `raspberry`,
    `raw sugar`,
    `reblochon`,
    `red bayberry`,
    `red beans`,
    `red cabbage`,
    `red clover`,
    `red kidney beans`,
    `red leicester`,
    `red lentils`,
    `red mombin`,
    `red mulberry`,
    `red pudding`,
    `red rice`,
    `red sangria`,
    `redcurrant`,
    `redcurrants`,
    `refined oils`,
    `refined sugars and flour`,
    `regal de la dombes`,
    `regensburger wurst`,
    `reggianito`,
    `regular fries`,
    `remedou`,
    `requeson`,
    `rhubarb`,
    `rib eye steak`,
    `riberry`,
    `riccioli`,
    `ricciolini`,
    `ricciutelle`,
    `rice bean`,
    `rice beans`,
    `rice cakes`,
    `rice ice cream`,
    `rice krispies`,
    `rice milk`,
    `rice`,
    `richelieu`,
    `ricotta cheese`,
    `ricotta salata`,
    `ricotta`,
    `ridder`,
    `ridge cucumber`,
    `ridged gourd`,
    `riesling`,
    `rigatoncini`,
    `rigatoni`,
    `righteye flounder`,
    `rigotte`,
    `rimu`,
    `ringriderpølse`,
    `riñones`,
    `rioja`,
    `roasted nuts and seeds`,
    `rocamadour`,
    `rock cod`,
    `rock melon`,
    `rocket`,
    `rockfish`,
    `rockmelon`,
    `rød pølse`,
    `roe`,
    `rollot`,
    `romaine lettuce`,
    `romano`,
    `romans part dieu`,
    `rombi`,
    `roncal`,
    `rookworst`,
    `roquefort`,
    `rose apple`,
    `rose hip`,
    `rose myrtle`,
    `rose`,
    `rose-leaf bramble`,
    `rosemary`,
    `rosette de lyon`,
    `rotelle`,
    `roule`,
    `rouleau de beaulieu`,
    `rowan`,
    `royalp tilsit`,
    `rubens`,
    `rum`,
    `rump`,
    `runner bean`,
    `runner beans`,
    `rustiche`,
    `rustinu`,
    `rutabaga`,
    `rutabagas`,
    `rye flour`,
    `rye`,
    `ryynimakkara`,
    `saaland pfarr`,
    `saanenkaese`,
    `sablefish`,
    `sabodet`,
    `sacha inchi`,
    `sacred earflower`,
    `saffron`,
    `saga`,
    `sage derby`,
    `sage`,
    `sageretia`,
    `sagnarelli`,
    `sagne 'ncannulate`,
    `sagnette`,
    `saguaro`,
    `sai gork`,
    `sai krok isan`,
    `sai ua`,
    `sainte maure`,
    `saint-marcellin`,
    `saint-nectaire`,
    `saint-paulin`,
    `sake`,
    `salad`,
    `salak`,
    `salal berry`,
    `salal berry`,
    `salami`,
    `salamin`,
    `salchicha huachana`,
    `salchicha`,
    `salchichón`,
    `salers`,
    `salmon`,
    `salmonberry`,
    `salsichão`,
    `salsify`,
    `salumi`,
    `sambuca`,
    `samphire`,
    `samso`,
    `san simon`,
    `sancerre`,
    `sanddab`,
    `sandpaper fig`,
    `sandwich`,
    `sangiovese`,
    `santol`,
    `sap sago`,
    `sapodilla`,
    `sapota`,
    `sapote`,
    `sardel`,
    `sardelka`,
    `sardine`,
    `sardines`,
    `sauternes`,
    `sauvignon blanc`,
    `sauvignon`,
    `sazerac`,
    `scallions`,
    `scallops`,
    `schnapps`,
    `scotch`,
    `screwdriver`,
    `sea weeds`,
    `seitan`,
    `self-rising flour`,
    `semolina flour`,
    `sesame oil`,
    `sesame seeds`,
    `sesame`,
    `sex on the beach`,
    `shallots`,
    `sherry`,
    `shiitake mushrooms`,
    `shin and leg`,
    `shiraz`,
    `shochu`,
    `shortening`,
    `shrimp`,
    `sidecar`,
    `silverside`,
    `simple syrup`,
    `sirloin`,
    `smirnoff`,
    `smoked salmon`,
    `smoked sausage`,
    `smoothies`,
    `soda`,
    `soju`,
    `sorghum`,
    `sour cream`,
    `southern comfort`,
    `soy cheese`,
    `soy ice cream`,
    `soy milk`,
    `soy yogurt`,
    `soybean oil`,
    `soybeans`,
    `spaghetti squash`,
    `sparkling water`,
    `special k`,
    `spelt`,
    `spinach`,
    `split peas`,
    `sports drinks`,
    `squash`,
    `squid`,
    `starfruit`,
    `stevia`,
    `stilton`,
    `stolichnaya`,
    `strawberries`,
    `strawberry jam`,
    `string cheese`,
    `sugarcane`,
    `summer squash`,
    `sunchokes`,
    `sunflower oil`,
    `sunflower seeds`,
    `sunflower`,
    `sushi rice`,
    `sweet corn`,
    `sweet potato fries`,
    `sweet potatoes`,
    `swiss chard`,
    `swiss`,
    `syrah`,
    `table salt`,
    `taco`,
    `taleggio`,
    `tanqueray`,
    `tapa de asado`,
    `tapa de nalga`,
    `taro`,
    `tarragon`,
    `t-bone steak`,
    `tea`,
    `teff`,
    `tempeh`,
    `tempranillo`,
    `tequila sunrise`,
    `tequila`,
    `thick flank`,
    `thick rib`,
    `thin rib`,
    `thyme`,
    `tilapia`,
    `tofu`,
    `tokaji`,
    `tomatoes`,
    `tongue`,
    `toor dal`,
    `top rump`,
    `topside`,
    `tortillas`,
    `touriga nacional`,
    `triple sec`,
    `trout`,
    `truffle mushrooms`,
    `tuna`,
    `turkey pastrami`,
    `turkey`,
    `turmeric`,
    `turnip greens`,
    `turnips`,
    `urad dal`,
    `vacío`,
    `vanilla`,
    `vegetable juice`,
    `vegetable oil`,
    `vegetable or fruit juice`,
    `vegetables`,
    `vegetarian pastrami`,
    `venison`,
    `verdejo`,
    `vermouth`,
    `vinegar`,
    `viognier`,
    `vodka`,
    `waffle`,
    `waffles`,
    `walnut oil`,
    `walnut`,
    `walnuts`,
    `water chestnuts`,
    `water`,
    `watercress`,
    `watermelons`,
    `wax beans`,
    `wensleydale`,
    `wheat grass`,
    `wheat`,
    `wheatgrass`,
    `wheaties`,
    `whipped cream`,
    `whiskey sour`,
    `whiskey`,
    `white beans`,
    `white radish`,
    `white sugar`,
    `whole wheat flour`,
    `wild rice`,
    `wine`,
    `winged beans`,
    `winter squash`,
    `wraps`,
    `xylitol`,
    `yacon syrup`,
    `yams`,
    `yellow lentils`,
    `yogurt`,
    `young coconut water`,
    `young coconut`,
    `yucca`,
    `zinfandel`,
    `zombie`,
    `zucchini`,

]
async function search(query) {

    const options = {
        method: 'GET',
        // url: 'https://calorieninjas.p.rapidapi.com/v1/nutrition',
        url: 'https://api.calorieninjas.com/v1/nutrition',
        params: { query },
        headers: {
            // 'X-RapidAPI-Key': NINJA_API_KEY,
            'X-Api-Key': NINJA_API_KEY,
            // 'X-RapidAPI-Host': 'calorieninjas.p.rapidapi.com'
        }
    };

    const result = await axios.request(options)
    // .then(function (response) {
    //     console.log(response.data)
    //     // return response.data
    // }).catch(function (error) {
    //     console.error(error);
    // });
    return result.data

}

async function postIngredient(data) {
    console.log("postIngredient", data.items[0])
    if (data.items[0] !== undefined) {
        const newIngredient = new PostNutrition(data.items[0])
        console.log("postIngredient newIngredient", data?.items[0]?.name)

        const findIngredient = await PostNutrition.find({ name: data?.items[0]?.name })

        console.log("findIngredient", findIngredient.length)

        const result = findIngredient.length === 0 ? await newIngredient.save() : console.log(data.items[0].name)

        console.log(result)
    }
}

async function getNinjaIngredients() {
    var missingIngredients = []
    const ninjaIngredientsList = await PostNutrition.find({})
    // console.log("ninjaIngredientsList", ninjaIngredientsList)

    ingredients.map(ingre => ninjaIngredientsList.every(item => item.name !== ingre) && missingIngredients.push(ingre))

    // console.log("missingIngredients", missingIngredients)
    missingIngredients.map((item, index) => (index > 150 && index <= 200) && console.log(item))
}

// getNinjaIngredients()

module.exports = { search, postIngredient, getNinjaIngredients };
