const mongoose = require("mongoose")

// const PostMyMail = require('../models/myMailsModel.js')

// const userModel = require("../models/userModel")
const nutritionLogic = require("../../BL/nutritionLogic")
// const ingredient = [
// "absinthe",
// "absolut",
// "acorn squash",
// "adzuki beans",
// "agave nectar",
// "Albariño",
// "almond butter",
// "almond flour",
// "almond ice cream",
// "almond milk",
// "almond yogurt",
// "almonds",
// "amaranth seeds",
// "amaranth",
// "amaretto",
// "anchovies",
// "andouille",
// "angostura bitters",
// "anise",
// "aperol spritz",
// "aperol",
// "apple butter",
// "apricot jam",
// "apricots",
// "arborio rice",
// "artichokes",
// "asiago",
// "asparagus",
// "avocado oil",
// "avocados",
// "bacardi",
// "bagels",
// "baijiu",
// "baileys",
// "bambara beans",
// "bananas",
// "Barbera",
// "barley",
// "basil",
// "basmati rice",
// "bay leaves",
// "beans",
// "beef tallow",
// "beef",
// "beets",
// "bell peppers",
// "bellini",
// "bison",
// "black beans",
// "black pepper",
// "black rice",
// "blackberries",
// "blackberry jam",
// "blackcurrants",
// "black-eyed peas",
// "blood sausage",
// "bloody mary",
// "blue cheese",
// "blue lagoon",
// "blue stilton",
// "blueberries",
// "blueberry jam",
// "boar",
// "boilermaker",
// "Bordeaux",
// "boudin",
// "bourbon",
// "boursin",
// "boysenberries",
// "brandy alexander",
// "brandy",
// "bratwurst",
// "bread flour",
// "bread",
// "breadfruit",
// "breakfast sausage",
// "brie cheese",
// "brie",
// "broccoli",
// "brown lentils",
// "brown rice syrup",
// "brown rice",
// "brown sugar",
// "brussels sprouts",
// "buckwheat",
// "bulgur",
// "Burgundy",
// "burrata",
// "butter beans",
// "butter",
// "butternut squash",
// "buttery nipple",
// "cabbage",
// "Cabernet Sauvignon",
// "cake flour",
// "camembert cheese",
// "camembert",
// "campari",
// "cane sugar",
// "cane syrup",
// "cannellini beans",
// "canola oil",
// "cantaloupes",
// "Cap'n Crunch",
// "captain morgan",
// "caraway",
// "cardamom",
// "carrots",
// "cashew ice cream",
// "cashew milk",
// "cashew yogurt",
// "cashews",
// "cassava",
// "catfish",
// "cauliflower",
// "cayenne pepper",
// "celery leaves",
// "celery",
// "cereal",
// "chamomile",
// "champagne cocktail",
// "champagne",
// "chana dal",
// "chard",
// "chartreuse",
// "cheddar cheese curds",
// "cheddar cheese sauce",
// "cheddar cheese",
// "cheddar jack",
// "cheddar spread",
// "Cheerios",
// "cheese",
// "Chenin Blanc",
// "cherries",
// "cherry preserves",
// "chestnuts",
// "chia seeds",
// "Chianti",
// "chickpea flour",
// "chickpeas",
// "chicory",
// "chili powder",
// "chives",
// "chocolate milk",
// "chocolate syrup",
// "chorizo",
// "cider",
// "cilantro",
// "Cinnamon Toast Crunch",
// "cinnamon",
// "Cinsault",
// "cinzano",
// "clams",
// "clementines",
// "cloves",
// "Cocoa Puffs",
// "coconut cream",
// "coconut flour",
// "coconut ice cream",
// "coconut milk",
// "coconut oil",
// "coconut sugar",
// "coconut water",
// "coconut yogurt",
// "cod",
// "coffee",
// "cognac",
// "cointreau",
// "colby",
// "collard greens",
// "common beans",
// "coriander",
// "corn flakes",
// "corn oil",
// "corn syrup",
// "corn",
// "cornmeal",
// "cosmopolitan",
// "cotija",
// "cottage cheese",
// "couscous",
// "cowpeas",
// "crab",
// "crackers",
// "cranberries",
// "cream cheese",
// "creme de cassis",
// "creme de menthe",
// "cremini mushrooms",
// "croissants",
// "cucumbers",
// "cumin",
// "daiquiri",
// "dandelion greens",
// "date sugar",
// "dates",
// "dill",
// "disaronno",
// "dried apples",
// "dried apricots",
// "dried bananas",
// "dried beans",
// "dried cherries",
// "dried cranberries",
// "dried figs",
// "dried fruits",
// "dried garlic",
// "dried herbs",
// "dried lentils",
// "dried mango",
// "dried mangoes",
// "dried meats",
// "dried mushrooms",
// "dried noodles",
// "dried onions",
// "dried papayas",
// "dried peas",
// "dried peppers",
// "dried prunes",
// "dried seaweed",
// "dried spices",
// "dried tomatoes",
// "duck eggs",
// "duck",
// "edam",
// "edamame",
// "eggplant",
// "eggs",
// "einkorn",
// "elderberries",
// "elk",
// "emmental",
// "emmer",
// "emu",
// "endive",
// "energy drinks",
// "enoki mushrooms",
// "erythritol",
// "escarole",
// "farro",
// "fava beans",
// "fennel seeds",
// "fennel",
// "fenugreek",
// "feta cheese",
// "feta",
// "fig preserves",
// "figs",
// "fish",
// "flaming dr. pepper",
// "flax seeds",
// "flaxseed oil",
// "flaxseeds",
// "fontina",
// "four horsemen",
// "frangelico",
// "frankfurter",
// "French 75",
// "french lentils",
// "Froot Loops",
// "Frosted Flakes",
// "fruit infused water",
// "fruit syrup",
// "fruit",
// "garbanzo beans",
// "garlic powder",
// "garlic",
// "Garnacha",
// "garrotxa",
// "Gewürztraminer",
// "gin and tonic",
// "gin fizz",
// "gin",
// "ginger",
// "goat cheese",
// "goat",
// "golden syrup",
// "goose eggs",
// "gooseberries",
// "gorgonzola",
// "gouda cheese",
// "gouda",
// "grand marnier",
// "granola",
// "grapefruits",
// "Grape-Nuts",
// "grapes",
// "grapeseed oil",
// "green beans",
// "green lentils",
// "green peas",
// "green tea shot",
// "Grenache",
// "Gruner Veltliner",
// "gruyere",
// "guavas",
// "halloumi",
// "havarti cheese",
// "havarti",
// "hazelnut oil",
// "hazelnuts",
// "hemp milk",
// "hemp seeds",
// "herbal tea",
// "herring",
// "Honey Nut Cheerios",
// "honey",
// "honeydew melons",
// "hot chocolate",
// "hot dog",
// "hummus",
// "hyacinth beans",
// "ice cream",
// "iced tea",
// "irish car bomb",
// "irish coffee",
// "jack beans",
// "jack daniels",
// "jägerbomb",
// "jägermeister",
// "jasmine rice",
// "jello shots",
// "jicama",
// "jim beam",
// "johnnie walker",
// "juice",
// "kahlua",
// "kale",
// "kamut",
// "kidney beans",
// "kielbasa",
// "kir royale",
// "kiwiberries",
// "kiwis",
// "knockwurst",
// "kohlrabi",
// "kombucha",
// "lamb",
// "lard",
// "lavender",
// "leeks",
// "lemonade",
// "lemongrass",
// "lemons",
// "lentils",
// "lettuce",
// "lima beans",
// "limes",
// "linguica",
// "liquid cocaine",
// "liverwurst",
// "lobster",
// "long island iced tea",
// "Lucky Charms",
// "lupin beans",
// "lychees",
// "macadamia nuts",
// "Madeira",
// "mai tai",
// "maitake mushrooms",
// "makers mark",
// "Malbec",
// "manchego",
// "mandarins",
// "mangoes",
// "mangosteens",
// "manhattan",
// "maple syrup",
// "margarine",
// "margarita",
// "marjoram",
// "martini & rossi",
// "martini",
// "masoor dal",
// "merguez",
// "Merlot",
// "mezcal margarita",
// "mezcal",
// "michelada",
// "midori",
// "milk",
// "millet",
// "mimosa",
// "mint",
// "mojito",
// "molasses",
// "Monastrell",
// "monk fruit sweetener",
// "monterey jack",
// "moong dal",
// "morel mushrooms",
// "Moscato",
// "moscow mule",
// "moth beans",
// "mother beans",
// "Mourvèdre",
// "mozzarella cheese",
// "mozzarella di bufala",
// "mozzarella",
// "muenster",
// "muffins",
// "mulberries",
// "Müller-Thurgau",
// "mung beans",
// "munster",
// "Muscat",
// "mushrooms",
// "mussels",
// "mustard greens",
// "mustard seeds",
// "mustard",
// "naan",
// "navy beans",
// "Nebbiolo",
// "noilly prat",
// "nut cheese",
// "nutmeg",
// "oat flour",
// "oat ice cream",
// "oat milk",
// "oats",
// "okra",
// "onion powder",
// "onion",
// "onions",
// "oranges",
// "oregano",
// "ouzo",
// "oyster mushrooms",
// "oysters",
// "painkiller",
// "palm oil",
// "paloma",
// "pancakes",
// "paneer",
// "papayas",
// "paprika",
// "parmesan cheese",
// "parmesan",
// "parsley",
// "parsnips",
// "passion fruit",
// "pasta",
// "pastis",
// "pastry flour",
// "patron",
// "pea milk",
// "peach preserves",
// "peaches",
// "peanut butter",
// "peanut oil",
// "peanuts",
// "pears",
// "peas",
// "pecans",
// "pepper jack",
// "persimmons",
// "Petit Verdot",
// "Petite Sirah",
// "pina colada",
// "piña colada",
// "pineapples",
// "Pinot Grigio",
// "Pinot Noir",
// "pinto beans",
// "pisco sour",
// "pisco",
// "pistachios",
// "pita bread",
// "plantain",
// "plum preserves",
// "plums",
// "polenta",
// "pomegranates",
// "popcorn",
// "poppy seeds",
// "pork",
// "port wine",
// "Port",
// "portobello mushrooms",
// "potato chips",
// "potatoes",
// "powdered sugar",
// "pretzels",
// "Prosecco",
// "provolone cheese",
// "provolone",
// "prunes",
// "pumpkin seeds",
// "pumpkin",
// "quail eggs",
// "quail",
// "quesadilla cheese",
// "queso blanco",
// "queso fresco",
// "quinoa seeds",
// "quinoa",
// "raclette",
// "radicchio",
// "radishes",
// "raisins",
// "raki",
// "rakia",
// "raspberries",
// "raspberry jam",
// "raw sugar",
// "red lentils",
// "red rice",
// "red sangria",
// "redcurrants",
// "regular fries",
// "rhubarb",
// "rice beans",
// "rice cakes",
// "rice ice cream",
// "Rice Krispies",
// "rice milk",
// "rice",
// "ricotta cheese",
// "ricotta salata",
// "ricotta",
// "Riesling",
// "Rioja",
// "romano",
// "rosemary",
// "rum",
// "rutabagas",
// "rye flour",
// "rye",
// "saffron",
// "sage",
// "sake",
// "salmon",
// "sambuca",
// "Sangiovese",
// "sardines",
// "Sauternes",
// "Sauvignon Blanc",
// "Sauvignon",
// "sazerac",
// "scallions",
// "scallops",
// "schnapps",
// "scotch",
// "screwdriver",
// "seitan",
// "self-rising flour",
// "semolina flour",
// "sesame oil",
// "sesame seeds",
// "sex on the beach",
// "shallots",
// "sherry",
// "shiitake mushrooms",
// "Shiraz",
// "shochu",
// "shortening",
// "shrimp",
// "sidecar",
// "simple syrup",
// "smirnoff",
// "smoked sausage",
// "smoothies",
// "soda",
// "soju",
// "sorghum",
// "sour cream",
// "southern comfort",
// "soy cheese",
// "soy ice cream",
// "soy yogurt",
// "soybean oil",
// "soybeans",
// "spaghetti squash",
// "sparkling water",
// "Special K",
// "spelt",
// "spinach",
// "split peas",
// "sports drinks",
// "squash",
// "squid",
// "starfruit",
// "stevia",
// "stolichnaya",
// "strawberries",
// "string cheese",
// "sunchokes",
// "sunflower oil",
// "sunflower seeds",
// "sushi rice",
// "sweet potato fries",
// "sweet potatoes",
// "swiss chard",
// "swiss",
// "Syrah",
// "taleggio",
// "tanqueray",
// "taro",
// "tarragon",
// "tea",
// "teff",
// "tempeh",
// "Tempranillo",
// "tequila sunrise",
// "tequila",
// "thyme",
// "tilapia",
// "tofu",
// "Tokaji",
// "tomatoes",
// "toor dal",
// "tortillas",
// "Touriga Nacional",
// "triple sec",
// "trout",
// "truffle mushrooms",
// "tuna",
// "turkey pastrami",
// "turkey",
// "turmeric",
// "turnip greens",
// "turnips",
// "urad dal",
// "vanilla",
// "vegetable juice",
// "vegetable oil",
// "vegetables",
// "vegetarian pastrami",
// "venison",
// "Verdejo",
// "vermouth",
// "Viognier",
// "vodka",
// "waffles",
// "walnut oil",
// "walnuts",
// "water chestnuts",
// "watercress",
// "watermelons",
// "wensleydale",
// "Wheaties",
// "whipped cream",
// "whiskey sour",
// "whiskey",
// "whole wheat flour",
// "wild rice",
// "wine",
// "winged beans",
// "wraps",
// "xylitol",
// "yams",
// "yellow lentils",
// "yogurt",
// "yucca",
// "Zinfandel",
// "zombie",
// "zucchini",
// "all-purpose flour",
// "almonds",
// "apples",
// "basil",
// "beef pastrami",
// "beer",
// "butter",
// "button mushrooms",
// "carrots",
// "Chardonnay",
// "cheddar",
// "chicken eggs",
// "chicken",
// "chickpeas",
// "cumin",
// "dried apricots",
// "dried cranberries",
// "dried fruit",
// "Italian sausage",
// "maple syrup",
// "milk",
// "oatmeal",
// "olive oil",
// "potatoes",
// "rice",
// "salmon",
// "soy milk",
// "strawberry jam",
// "sunflower seeds",
// "water",
// "wheat",
// "white sugar",
// ]
// const ingredient = [
// `Abalone`,
// `Abbaye de Belloc`,
// `Abbaye de Citeaux`,
// `Abbaye du Mont des Cats`,
// `Abertam`,
// `Abiu`,
// `Abondance`,
// `Aburana`,
// `Açaí`,
// `Acapella`,
// `Acerola`,
// `Ackawi`,
// `Ackee`,
// `Acorn`,
// `Acorn Squash`,
// `Adelost`,
// `Affidelice au Chablis`,
// `African Cherry Orange`,
// `Afuega'l Pitu`,
// `Aging salumi`,
// `ahipa`,
// `Ahle Wurst`,
// `Airag`,
// `Airedale`,
// `Aisy Cendre`,
// `Ajowan`,
// `Akebi`,
// `Alaminos longganisa`,
// `Alaskan pollock`,
// `Alaskan salmon`,
// `albacore tuna`,
// `alfalfa sprouts`,
// `Alheira`,
// `Allgauer Emmentaler`,
// `Alligator Apple`,
// `Allspice`,
// `Almond`,
// `Alverca`,
// `amaranth`,
// `Amazon Grape`,
// `Ambarella`,
// `Ambert`,
// `Amchur`,
// `American Cheese`,
// `American elderberry`,
// `American ground nut`,
// `American Groundnut`,
// `American Mayapple`,
// `Ami du Chambertin`,
// `Ananas`,
// `Anchovies`,
// `Andouille`,
// `Andouillette`,
// `Androlla`,
// `Anejo Enchilado`,
// `Anelli`,
// `Angelica`,
// `Anglerfish`,
// `Anise`,
// `Aniseed`,
// `Annatto`,
// `Anneau du Vic-Bilh`,
// `Anthoriro`,
// `aonori`,
// `Appenzell`,
// `Apple`,
// `Apricot`,
// `Arabiki`,
// `Aragon`,
// `Araza`,
// `Ardi Gasna`,
// `Ardrahan`,
// `Arhat`,
// `Armenian String`,
// `Aromes au Gene de Marc`,
// `arracacha`,
// `artichoke`,
// `arugula`,
// `Asadero`,
// `Asafoetida`,
// `ash gourd`,
// `Asiago`,
// `asparagus`,
// `Atemoya`,
// `aubergine`,
// `Aubergines`,
// `Aubisque Pyrenees`,
// `Autun`,
// `Avaxtskyr`,
// `Avocado`,
// `Avocados`,
// `Azaruja sausage`,
// `Azuki Bean`,
// `azuki beans`,
// `Babaco`,
// `Babic`,
// `Baby Swiss`,
// `Babybel`,
// `badderlocks`,
// `Bael`,
// `Baguette Laonnaise`,
// `Baguio longganisa`,
// `Bakers`,
// `Baladi`,
// `Balaton`,
// `Balkenbrij`,
// `Bamboo Shoot`,
// `Banana`,
// `Banana blossom`,
// `banana squash`,
// `Banat sausage`,
// `Bandal`,
// `Banon`,
// `Barbadine`,
// `Barbados Cherry`,
// `Barberry`,
// `Barnacles`,
// `Barracuda`,
// `Barry's Bay Cheddar`,
// `Basa`,
// `Basil`,
// `Basing`,
// `Basket Cheese`,
// `Bass`,
// `Bath Cheese`,
// `Battered sausage`,
// `Bavarian Bergkase`,
// `Bavette`,
// `Bay Leaf`,
// `bay scallop`,
// `Bayberry`,
// `Baylough`,
// `Beach Plum`,
// `Bean`,
// `bean sprouts`,
// `Bearberry`,
// `Beaufort`,
// `Beauvoorde`,
// `Bee balm`,
// `beech nut`,
// `Beechnut`,
// `Beef sausage`,
// `Beenleigh Blue`,
// `Beer Cheese`,
// `Beet`,
// `beet greens`,
// `beet `,
// `beetroot`,
// `Bel Paese`,
// `Bell pepper`,
// `Belutak`,
// `Bergader`,
// `Bergamot`,
// `Bergere Bleue`,
// `Berkswell`,
// `Berry`,
// `betel`,
// `Betel Nut`,
// `Bethmale des Pyrénées`,
// `Bethmale of the Pyrenees`,
// `Beutelwurst`,
// `Beyaz Peynir`,
// `Bierkase`,
// `Bierschinken`,
// `Bierwurst`,
// `bigeye tuna`,
// `Bignay`,
// `Bigoli`,
// `Bilberry`,
// `Bilimbi`,
// `Biroldo`,
// `Bishop Kennedy`,
// `Bishops weed `,
// `bitter gourd`,
// `bitter melon`,
// `Bitterleaf`,
// `Black Apple`,
// `black beans`,
// `Black Cherry`,
// `Black cod`,
// `Black Cumin`,
// `Black Lime`,
// `Black Mulberry`,
// `Black Mustard`,
// `Black Pepper`,
// `Black pudding`,
// `Black Raspberry`,
// `Black sapote`,
// `Blackberry`,
// `Blackcurrant`,
// `Black-eyed Pea`,
// `Blarney`,
// `Bleu d'Auvergne`,
// `Bleu de Gex`,
// `Bleu de Laqueuille`,
// `Bleu de Septmoncel`,
// `Bleu de Termignon Alpage`,
// `Bleu Des Causses`,
// `Blodpølse`,
// `Blóðpylsa`,
// `Bloedworst`,
// `Blood orange`,
// `Blood sausage Krov'janka`,
// `Blue`,
// `Blue Castello`,
// `Blue of Termignon`,
// `Blue Rathgore`,
// `Blue Tongue`,
// `Blueberry`,
// `bluefin tuna`,
// `Bluefish`,
// `Blunze`,
// `Blutwurst`,
// `Boccoli`,
// `Bocconcini`,
// `Bockwurst`,
// `Boeren Leidenkaas`,
// `Boerewors`,
// `bok choy`,
// `Boldo`,
// `Bologna sausage`,
// `Bolwarra`,
// `Bombay duck`,
// `Bonchester`,
// `Bonito`,
// `Borage`,
// `borage greens`,
// `Borlotti Beans`,
// `Bosworth`,
// `Botillo`,
// `bottle gourd`,
// `Boudin`,
// `Boudin blanc de Rethel`,
// `Bougon`,
// `Boule Du Roves`,
// `Boulette d'Avesnes`,
// `Boursault`,
// `Boursin`,
// `Bouyssou`,
// `Boysenberry`,
// `Bra`,
// `Braadworst`,
// `Braai Wors`,
// `Bramble`,
// `Brativurst`,
// `Bratwurst`,
// `Braudostur`,
// `Braughing sausage`,
// `Braunschweiger`,
// `Brazil Nut`,
// `Breadfruit`,
// `breadnut`,
// `Breakfast Cheese`,
// `Breakfast sausage`,
// `Bream`,
// `Brebis du Lavort`,
// `Brebis du Lochois`,
// `Brebis du Puyfaucon`,
// `Bregenwurst`,
// `Bresse Bleu`,
// `Brick`,
// `Brie`,
// `Brie au poivre`,
// `Brie de Meaux`,
// `Brie de Melun`,
// `Brie with pepper`,
// `Brill`,
// `Brillat-Savarin`,
// `Brin`,
// `Brin d'Amour`,
// `Brinjal`,
// `Brinza`,
// `Briquette de Brebis`,
// `Briquette du Forez`,
// `broad beans`,
// `broadleaf arrowhead`,
// `Broadleaf Bramble`,
// `Broccio`,
// `Broccio Demi-Affine`,
// `broccoflower`,
// `broccoli`,
// `Broccoli Rabe`,
// `Brousse du Rove`,
// `Bruder Basil`,
// `Brühwurst`,
// `Brussel Sprout`,
// `Brusselae Kaas`,
// `brussels sprouts`,
// `Bryndza`,
// `Bucatini`,
// `Buchette d'Anjou`,
// `Buddha’s hand fruit`,
// `Buddha's hand`,
// `Buffalo`,
// `Buffaloberry`,
// `Bulls Blood`,
// `Bunnings Sausage`,
// `Burbot`,
// `Burdekin Plum`,
// `Burdock`,
// `Burgos`,
// `Burmese Grape`,
// `Bush Tomato`,
// `Busiate`,
// `Butifarra`,
// `Butifarra Soledeñas`,
// `Butte`,
// `butter bean`,
// `Butter Beans`,
// `buttercup squash`,
// `butterfly tree`,
// `Butterhead Lettuce`,
// `Butterkase`,
// `Butternut Pumpkin`,
// `butternut squash`,
// `Button`,
// `Buxton Blue`,
// `Cabanatuan longganisa`,
// `cabbage`,
// `Cabecou`,
// `Caboc`,
// `Cabrales`,
// `Cacao`,
// `Cachaille`,
// `Caciocavallo`,
// `Caciotta`,
// `Cactus pear`,
// `Caerphilly`,
// `Caigua`,
// `Caimito`,
// `Cairnsmore`,
// `Cajamanga`,
// `Cajna`,
// `Calabashtree`,
// `Calabrese`,
// `Calamarata`,
// `Calamus`,
// `Calenzana`,
// `Calumpit longganisa`,
// `camas`,
// `Cambazola`,
// `Camembert`,
// `Camomile`,
// `Campanelle or torchio`,
// `Camucamu`,
// `Canadian Cheddar`,
// `Canary melon`,
// `candlenut`,
// `Canestrato`,
// `Canistel`,
// `canna`,
// `Cantal`,
// `Cantaloupe`,
// `Cape gooseberry`,
// `Capellini`,
// `Capers`,
// `Cappelli da chef`,
// `Caprice des Dieux`,
// `Capricorn Goat`,
// `Capriole Banon`,
// `Capsicum`,
// `Carambola`,
// `Caravane`,
// `Caraway`,
// `Cardamom`,
// `Cardamon`,
// `Cardon`,
// `Cardoon`,
// `Carnation`,
// `Carob`,
// `carola`,
// `Carre de l'Est`,
// `carrot`,
// `Casarecce`,
// `Cascatelli`,
// `Casciotta di Urbino`,
// `Cashel Blue`,
// `Cashew`,
// `Cashew nut`,
// `Cassava`,
// `Cassia`,
// `Castellane`,
// `Castelleno`,
// `Castelmagno`,
// `Castelo Branco`,
// `Castigliano`,
// `Catfish`,//
// `Cathelain`,
// `catsear`,
// `cauliflower`,
// `Cavatappi`,
// `Cavatelli`,
// `Caviar`,
// `Caviar Lime`,
// `Cayenne Pepper`,
// `ceci beans`,
// `Cedar Bay Cherry`,
// `celeriac`,
// `celery`,
// `Celtic Promise`,
// `celtuce`,
// `Cempedak`,
// `Cencioni`,
// `Cendre d'Olivet`,
// `Cephalopods`,
// `Cerney`,
// `Cervela`,
// `Cervelas de Lyon`,
// `Cervelat`,
// `Cervelatwurst`,
// `Cervellata`,
// `Češnovka`,
// `Ceylon Gooseberry`,
// `Cha`,
// `Cha com`,
// `Cha lua`,
// `Chabichou`,
// `Chabichou du Poitou`,
// `Chabis de Gatine`,
// `chamomile`,
// `Champagne Melon`,
// `Chaource`,
// `Char`,
// `chard`,
// `Charolais`,
// `Chaudin`,
// `Chaumes`,
// `chaya`,
// `Chayote`,
// `Che`,
// `Cheddar`,
// `Cheddar Clothbound`,
// `Chempedak`,
// `Chenet`,
// `Cherimoya`,
// `Cherry`,
// `Cherry Tomato`,
// `Chervil`,
// `Cheshire`,
// `Chestnut`,
// `Chevres`,
// `Chevrotin des Aravis`,
// `Chia seeds`,
// `Chick Pea`,
// `Chicken longganisa`,
// `chickpeas`,
// `chickweed`,
// `Chico fruit`,
// `Chicory`,
// `Chifferi`,
// `Chile pepper`,
// `Chile Varieties`,
// `Chilean sea bass`,
// `Chili`,
// `chili pepper`,
// `Chilies`,
// `Chinese artichoke`,
// `Chinese Bayberry`,
// `Chinese Cabbage`,
// `Chinese Chives`,
// `Chinese hibiscus`,
// `chinese mallow`,
// `Chinese Mulberry`,
// `Chinese okra`,
// `Chipolata`,
// `Chistorra`,
// `Chives`,
// `Chocolate pudding fruit`,
// `Chokeberry`,
// `Chontaleno`,
// `Chorizo`,
// `Chorizo de Bilbao`,
// `Chorizo de Cebu`,
// `Chorizo de Macao`,
// `Chorizo Negrense`,
// `Chouriço`,
// `Chouriço doce`,
// `Choy Sum`,
// `Chrysanthemum`,
// `Chrysanthemum Leaves`,
// `Chunchullo`,
// `Ciauscolo`,
// `Ciavar`,
// `Cicioneddos`,
// `Cilantro`,
// `Cinnamon`,
// `Citron`,
// `Civray`,
// `Clam`,
// `Clementine`,
// `Cloudberry`,
// `Clove`,
// `Cluster Fig`,
// `Cockle`,
// `Coco De Mer`,
// `Coconut`,
// `Cocoplum`,
// `Cod`,
// `Coeur de Camembert au Calvados`,
// `Coeur de Chevre`,
// `Coffee`,
// `Cojack`,
// `Colby`,
// `Colby-Jack`,
// `Cold Pack`,
// `collard greens`,
// `Collards`,
// `Common Apple-Berry`,
// `Common bean`,
// `Common dandelion`,
// `Common sage`,
// `Common violet`,
// `Comte`,
// `Conch`,
// `Conchiglie`,
// `Conkerberry`,
// `Coolea`,
// `Cooleney`,
// `Coquetdale`,
// `Coral Lettuce`,
// `Coriander`,
// `Corleggy`,
// `corms`,
// `Corn`,
// `Corn kernel`,
// `Corn nuts`,
// `Cornelian Cherry`,
// `Cornflower`,
// `Cornish Pepper`,
// `Corzetti`,
// `Cos Lettuce`,
// `Cotechino`,
// `Cotechino Modena`,
// `Cotherstone`,
// `Cotija`,
// `Cottage Cheese`,
// `Cougar Gold`,
// `Coulommiers`,
// `courgette`,
// `Coverdale`,
// `Crab apple`,
// `Crabapple`,
// `Crabs`,
// `Cranberry`,
// `Craw`,
// `Cray Fish`,
// `Crayeux de Roncq`,
// `Cream Cheese`,
// `Cream Havarti`,
// `Crema Agria`,
// `Crema Mexicana`,
// `Creme Fraiche`,
// `Crescenza`,
// `Cress`,
// `Creste di galli`,
// `Croghan`,
// `Crottin de Chavignol`,
// `Crowberry`,
// `Crowdie`,
// `Crowley`,
// `Crustaceans`,
// `Csabai`,
// `Cuajada`,
// `Cubeb`,
// `Cucumber`,
// `Cucurbits`,
// `Cudpahnut`,
// `Cudrang`,
// `Cudrania`,
// `Cumberland sausage`,
// `Cumin`,
// `Cupuacu`,
// `Curd`,
// `Cure Nantais`,
// `Currant`,
// `Curry Leaf`,
// `Curworthy`,
// `Custard apple`,
// `Custard Squash`,
// `Cuttlefish`,
// `Cwmtawe Pecorino`,
// `cymbopogon`,
// `Cypress Grove Chevre`,
// `daikon`,
// `daikon`,
// `white radish`,
// `Daisy`,
// `Damson`,
// `Danablu`,
// `Danbo`,
// `Dandelion`,
// `Danish Fontina`,
// `Daralagjazsky`,
// `Date`,
// `Date Palm`,
// `Date-Plum`,
// `Dates`,
// `Dauphin`,
// `Davidson's Plum`,
// `Daylily`,
// `Debrecener`,
// `delicata`,
// `Delice des Fiouves`,
// `Denhany Dorset Drum`,
// `Derby`,
// `Desert Fig`,
// `Desert Lime`,
// `Dessertnyj Belyj`,
// `Devon`,
// `Devon Blue`,
// `Devon Garland`,
// `Dewberry`,
// `Dill`,
// `Dill Pickle`,
// `Diot`,
// `Dogfish`,
// `dogtooth tuna`,
// `Doh snam`,
// `Doi`,
// `Doktorskaya kolbasa`,
// `Dolcelatte`,
// `dolichos bean`,
// `Doolin`,
// `Doppelrhamstufel`,
// `Dorade`,
// `Dorset Blue Vinney`,
// `Doubah`,
// `Double Gloucester`,
// `Double Worcester`,
// `Dragon fruit`,
// `Dragon sausage`,
// `Dragonfruit`,
// `Dragonrfruit`,
// `Dreux a la Feuille`,
// `Dried coconut`,
// `dried plum`,
// `Drisheen`,
// `Droewors`,
// `drumstick`,
// `Dry Jack`,
// `Dry plums`,
// `Duddleswell`,
// `dudhi`,
// `Dulse`,
// `Dunbarra`,
// `Dunlop`,
// `Dunsyre Blue`,
// `Durain`,
// `Durian`,
// `Duroblando`,
// `Durrus`,
// `Dutch Mimolette`,
// `earthnut pea`,
// `Eastern May Hawthorn`,
// `Edam`,
// `Edamame`,
// `eddoe`,
// `Edelpilz`,
// `Eel`,
// `Egg fruit`,
// `Eggfruit`,
// `Eggplant`,
// `Elder`,
// `Elderberry`,
// `Elephant Apple`,
// `elephant foot yam`,
// `Elephant Garlic`,
// `Elim Wors`,
// `Emblic`,
// `Embutido`,
// `Emental Grand Cru`,
// `Emlett`,
// `Emmental`,
// `Emu Apple`,
// `endive`,
// `ensete`,
// `Entawak`,
// `Epazote`,
// `Epoisses de Bourgogne`,
// `Esbareich`,
// `Escarole`,
// `Esrom`,
// `Etorki`,
// `Etrog`,
// `Evansdale Farmhouse Brie`,
// `Evora De L'Alentejo`,
// `Exmoor Blue`,
// `Explorateur`,
// `Extrawurst`,
// `Fagioloni`,
// `Fainelle`,
// `falsa`,
// `Falukorv`,
// `Farfalle`,
// `Farinheira`,
// `Farmer`,
// `fat hen`,
// `Fava Bean`,
// `fava greens`,
// `Fazzoletti`,
// `Fedelini`,
// `Feijoa`,
// `Fennel`,
// `Fenugreek`,
// `fenugreek greens`,
// `Ferrazzuoli`,
// `Festoni`,
// `Feta`,
// `Fettuccine`,
// `Fibrous Satinash`,
// `Fiddlehead`,
// `fiddleheads`,
// `Fig`,
// `Figs`,
// `Figue`,
// `Fiji Longan`,
// `Fileja`,
// `Filetta`,
// `Fin-de-Siecle`,
// `Finger Lime`,
// `Finlandia Swiss`,
// `Finn`,
// `Fiore Sardo`,
// `Fiorentine`,
// `Fiori`,
// `Fish longganisa`,
// `Fish sausage`,
// `Fläskkorv`,
// `Flax seeds`,
// `Fleischwurst`,
// `Lyoner`,
// `Fleur du Maquis`,
// `Flor de Guia`,
// `Florence Fennel`,
// `Flounder`,
// `Flower Marie`,
// `Flowering Cabbage`,
// `fluted pumpkin`,
// `Foglie d'ulivo`,
// `Folded`,
// `Folded Cheese with Mint`,
// `Fondant de Brebis`,
// `Fontainebleau`,
// `Fontal`,
// `Fontina Val d'Aosta`,
// `Formaggio di Capra`,
// `Fougerus`,
// `Four Herb Gouda`,
// `Fourme d' Ambert`,
// `Fourme de Haute Loire`,
// `Fourme de Montbrison`,
// `Fox nuts`,
// `Frankfurter Rindswurst`,
// `Frankfurter Würstchen`,
// `French Bean`,
// `French marigold`,
// `Fresh Jack`,
// `Fresh Mozzarella`,
// `Fresh Ricotta`,
// `Fresh Truffles`,
// `Fribourgeois`,
// `Friesekaas`,
// `Friesian`,
// `Friesla`,
// `Frikandel`,
// `Frinault`,
// `frisee`,
// `Frizzmo`,
// `Fromage a Raclette`,
// `Fromage Corse`,
// `Fromage de Montagne de Savoie`,
// `Fromage Frais`,
// `Fruit Cream Cheese`,
// `Frying Cheese`,
// `Fuet`,
// `Fugu`,
// `Fusilli`,
// `Fusilli bucati`,
// `Fuyu Persimmon`,
// `Fynbo`,
// `Gabriel`,
// `Galangal`,
// `Galendar`,
// `Galette du Paludier`,
// `Galette Lyonnaise`,
// `Galia`,
// `Galia melon`,
// `Galloway Goat's Milk Gems`,
// `Gammelost`,
// `Gandaria`,
// `Gaperon a l'Ail`,
// `garbanzos`,
// `Garden nasturtium`,
// `Garden Pea`,
// `Garden Rocket`,
// `Garganelli`,
// `garlic`,
// `Garrotxa`,
// `Gastanberra`,
// `Geitost`,
// `Gelbwurst`,
// `gem squash`,
// `Gemelli`,
// `Genip`,
// `Genipap`,
// `Genoa salami`,
// `Geranium`,
// `Gherkin`,
// `Giant Granadilla`,
// `ginger`,
// `Gippsland Blue`,
// `Gjetost`,
// `Glamorgan sausage`,
// `Globe Artichokes`,
// `Gloucester`,
// `Gloucester sausage`,
// `Gnocchi`,
// `Goan Sausage`,
// `Gobo`,
// `Goetta`,
// `Goji berry`,
// `Golden Apple`,
// `Golden Cross`,
// `Golden kiwi`,
// `Golden Nugget Squash`,
// `golden samphire`,
// `Gomiti`,
// `gonjura`,
// `good king henry`,
// `Gooseberries`,
// `Gooseberry`,
// `Gorgonzola`,
// `Gornyaltajski`,
// `Gospel Green`,
// `Gouda`,
// `Goumi`,
// `Gourds`,
// `Goutu`,
// `Gowrie`,
// `Grabetto`,
// `Grabouw Wors`,
// `Graddost`,
// `Grafton Village Cheddar`,
// `Grana`,
// `Grana Padano`,
// `Grand Vatel`,
// `Grape`,
// `Grapefruit`,
// `Grapes`,
// `Grapple`,
// `Grataron d' Areches`,
// `Gratte-Paille`,
// `Graviera`,
// `Green apple`,
// `green beans`,
// `Green gooseberry`,
// `Green grapes`,
// `green onion`,
// `Greenbeans`,
// `Greengage`,
// `Greengage plum`,
// `greens`,
// `Grenadilla`,
// `Greuilh`,
// `Greve`,
// `Grewia asiatica`,
// `Grillpølse`,
// `Grillworst`,
// `Gris de Lille`,
// `Grouper`,
// `Gruyere`,
// `Guagua longganisa`,
// `Guanabana`,
// `guar`,
// `Guarana`,
// `Guava`,
// `Guavaberry`,
// `Guavasteen`,
// `Gubbeen`,
// `Guerbigny`,
// `Gyulai`,
// `habanero`,
// `Habenero Pepper`,
// `Hackberry`,
// `Haddock`,
// `Haggis`,
// `Hake`,
// `Hala Fruit`,
// `Halibut`,
// `Halloumi`,
// `Hamburg Parsley`,
// `Harbourne Blue`,
// `Hardy Kiwi`,
// `Haricot Beans`,
// `Havarti`,
// `Hawthorn`,
// `Hawthorn Berry`,
// `Hazelnut`,
// `Hazelnuts`,
// `Heart's ease`,
// `Heidi Gruyere`,
// `herbs`,
// `Hereford Hop`,
// `Herrgardsost`,
// `Herring`,
// `herring `,
// `Herriot Farmhouse`,
// `Herve`,
// `Hijiki`,
// `Hipi Iti`,
// `Hog maw`,
// `Hog Plum`,
// `Hog's pudding`,
// `Hoja Santa`,
// `Honeyberries`,
// `Honeyberry`,
// `Honeycrisp Apple`,
// `Honeydew`,
// `Honeydew melon`,
// `Honeysuckle`,
// `Horned Melon`,
// `horse gram`,
// `horseradish`,
// `Hot dog`,
// `Hot link`,
// `Hot-House Cucumber`,
// `hubbard squash`,
// `Hubbardston Blue Cow`,
// `Huckleberry`,
// `Huito`,
// `Humboldt Fog`,
// `Hungarian sausages`,
// `Hurka`,
// `Hushallsost`,
// `Husk cherry`,
// `Hyssop`,
// `Iberico`,
// `Ice Apple`,
// `Ice Plant`,
// `Iceberg Lettuce`,
// `Idaho Goatster`,
// `Idiazabal`,
// `Ikura`,
// `Il Boschetto al Tartufo`,
// `Ile d'Yeu`,
// `Ilish`,
// `Illawarra Plum`,
// `Inca berry`,
// `Indian Almond`,
// `Indian cress`,
// `Indian Fig`,
// `Indian Jujube`,
// `Indian Pea`,
// `Indian Prune`,
// `Indian Strawberry`,
// `Ironbark Pumpkin`,
// `Isle of Mull`,
// `Isterband`,
// `Ita Palm`,
// `Italian Red Onion`,
// `Italian sausage`,
// `ivy gourd`,
// `Jaboticaba`,
// `Jabuticaba`,
// `Jackfruit`,
// `Jagdwurst`,
// `Jagua`,
// `Jalapeño`,
// `Jalapeno Pepper`,
// `Jamaica Cherry`,
// `Jamaican Sorrel`,
// `Jambu`,
// `Jambul`,
// `Japanese amberjack`,
// `Japanese Bayberry`,
// `Japanese Bunching Onions`,
// `Japanese butterfish`,
// `Japanese honeysuckle`,
// `Japanese plum`,
// `Japanese Pumpkin`,
// `Japanese Raisin`,
// `Jarlsberg`,
// `Jasmine`,
// `Jatoba`,
// `Jausenwurst`,
// `Jelito`,
// `Jenipapo`,
// `Jermi Tortes`,
// `jerusalem artichoke`,
// `Jibneh Arabieh`,
// `jicama`,
// `Jindi Brie`,
// `Jocote`,
// `John Dory`,
// `Jostaberry`,
// `Jubilee Blue`,
// `Jujube`,
// `June Plum`,
// `Juniper`,
// `Juniper berry`,
// `Juustoleipa`,
// `Kabanos`,
// `Kabosu`,
// `Kadchgall`,
// `Kaffir lime`,
// `Kahikatea`,
// `Kai-lan`,
// `Kakadu Lime`,
// `Kakadu Plum`,
// `kale`,
// `Kandis Fruit`,
// `Kanga Bangas`,
// `Karkalla`,
// `karuka`,
// `Käsekrainer`,
// `Kaseri`,
// `Kashta`,
// `Kaszanka`,
// `Kazunoko`,
// `Kefalotyri`,
// `Kenafa`,
// `Keppel Fruit`,
// `Kernhem`,
// `Kervella Affine`,
// `Key Lime`,
// `Kidney Bean`,
// `kidney beans`,
// `Kielbasa`,
// `Kiełbasa biała`,
// `Kiełbasa jałowcowa`,
// `Kiełbasa myśliwska`,
// `Kiełbasa wędzona`,
// `Kikorangi`,
// `King Island Cape Wickham Brie`,
// `King River Gold`,
// `Kishka`,
// `Kiwano`,
// `Kiwi`,
// `Kiwi fruit`,
// `Kiwifruit`,
// `Klosterkaese`,
// `Knackwurst`,
// `Knakworst`,
// `Knipp`,
// `Knoblewurst`,
// `Knockalara`,
// `Kochwurst`,
// `kohlrabi`,
// `Kohlwurst`,
// `Kokum`,
// `kola nut`,
// `komatsuna`,
// `Kombu`,
// `konjac`,
// `Kosher Pickle`,
// `Krakowska`,
// `Krispy`,
// `Krvavnička`,
// `Kugelkase`,
// `kuka`,
// `Kulen`,
// `Kumquat`,
// `Kundong`,
// `Kupati`,
// `Kurobuta`,
// `Kurrat`,
// `Kutjera`,
// `La Taupiniere`,
// `La Vache Qui Rit`,
// `Lablab`,
// `Lady Apple`,
// `Lagane`,
// `lagos bologi`,
// `Laguiole`,
// `Lairobell`,
// `Lajta`,
// `Lamprey`,
// `Lanark Blue`,
// `Lancashire`,
// `Land Cress`,
// `Landjäger`,
// `Langres`,
// `Langsat`,
// `Lanterne`,
// `Lanzones`,
// `Lao sausage`,
// `Lạp xưởng`,
// `Lappi`,
// `Lapsi`,
// `Laruns`,
// `Lasagna`,
// `Lasagnette`,
// `Lasagnotte`,
// `lavender`,
// `laver`,
// `L'Aveyronnais`,
// `Lavistown`,
// `Le Brin`,
// `Le Fium Orbo`,
// `Le Lacandou`,
// `Le Roule`,
// `Leafield`,
// `Lebanese Cucumber`,
// `Lebanon bologna`,
// `Lebbene`,
// `Leberkäse`,
// `Leberwurst`,
// `L'Ecir de l'Aubrac`,
// `leek`,
// `Leerdammer`,
// `Legume`,
// `legumes`,
// `Leicester`,
// `Lekor`,
// `Lemon`,
// `Lemon Aspen`,
// `Lemon Balm`,
// `Lemon Grass`,
// `Lemon Myrtle`,
// `Lemon plum`,
// `Lemon Verbena`,
// `lemongrass`,
// `lentils`,
// `lettuce`,
// `Leucaena`,
// `Leyden`,
// `Licorice`,
// `Likëngë`,
// `Lilac`,
// `Lillipilli`,
// `Lilly Pilly`,
// `Lima Bean`,
// `lima beans`,
// `Limburger`,
// `Lime`,
// `Lincolnshire Poacher`,
// `Lincolnshire sausage`,
// `Linden, etc.`,
// `Lingcod`,
// `Lingonberry`,
// `Lingot Saint Bousquet d'Orb`,
// `Linguiça`,
// `Linguine`,
// `Liptauer`,
// `Liptovská saláma`,
// `Little Rydings`,
// `Livarot`,
// `Liverwurst`,
// `lizard’s tail`,
// `Lizard's Tail`,
// `Llanboidy`,
// `Llanglofan Farmhouse`,
// `Lobsters`,
// `Loch Arthur Farmhouse`,
// `Loco`,
// `Loddiswell Avondale`,
// `Loganberry`,
// `Longan`,
// `Longaniza`,
// `Longaniza de Guinobatan`,
// `Longganisa`,
// `Longhorn`,
// `loofah`,
// `Loomi`,
// `Loquat`,
// `Lorighittas`,
// `Lorne sausage`,
// `Lotus Root`,
// `Lou Palou`,
// `Lou Pevre`,
// `Loukaniko`,
// `Lovage`,
// `Lucban longganisa`,
// `Lucuma`,
// `luffa`,
// `Luganega`,
// `Lukanka`,
// `Lulo`,
// `Lumpfish roe`,
// `Lunenburg pudding`,
// `Lychee`,
// `Lyonnais`,
// `Maasdam`,
// `Mabolo`,
// `Macadamia`,
// `Macadamia nuts`,
// `Macaroni`,
// `Maccheroncelli`,
// `Maccheroncini di Campofilone`,
// `Maccheroni alla molinara`,
// `Macconais`,
// `Mace`,
// `Mackerel`,
// `Mafalde`,
// `Mafaldine`,
// `Magellan Barberry`,
// `Mahi Mahi`,
// `Mahi-mahi`,
// `Mahlab`,
// `Mahoe Aged Gouda`,
// `Mahon`,
// `Maize`,
// `Makanek`,
// `Makrut Lime`,
// `malabar chestnut`,
// `Malabar Gourd`,
// `malabar spinach`,
// `Malay Apple`,
// `Malloreddus`,
// `Maltagliati`,
// `Malvern`,
// `Mamey Apple`,
// `Mamey Sapote`,
// `Mamin Chino`,
// `Mamirolle`,
// `Mamoncillo`,
// `Manchego`,
// `Manchester sausage`,
// `Mandala`,
// `Mandarin`,
// `Mandarin orange`,
// `Mandarine`,
// `mange tout`,
// `mangelwurzel`,
// `Mango`,
// `Mangosteen`,
// `Manila Tamarind`,
// `Manoao`,
// `Manouri`,
// `Manur`,
// `Marang`,
// `Marble Cheddar`,
// `Marbled Cheeses`,
// `Marcona almonds`,
// `Maredsous`,
// `Margotin`,
// `Maribo`,
// `Marigold`,
// `Marille`,
// `Marion Berry`,
// `Marionberry`,
// `marjoram`,
// `Maroilles`,
// `marrow`,
// `Marylebone sausage`,
// `Masago`,
// `Mascares`,
// `Mascarpone`,
// `Mascarpone Torta`,
// `mashua`,
// `Mastic`,
// `Matocq`,
// `Matriciani`,
// `Mayapple`,
// `Mayhaw`,
// `Maypop`,
// `Maytag Blue`,
// `Mazzafegati`,
// `Medisterpølse`,
// `Medlar`,
// `Medlar fruit`,
// `Meira`,
// `Melegueta Pepper`,
// `Melinjo`,
// `melokhia`,
// `Melon`,
// `Melon Pear`,
// `Menallack Farmhouse`,
// `Menonita`,
// `Meredith Blue`,
// `Merguez`,
// `Mesost`,
// `Metton`,
// `Mettwurst`,
// `Metworst`,
// `Meyer Vintage Gouda`,
// `Mezzani`,
// `Mezze maniche`,
// `Mezze penne`,
// `Mezzi bombardoni`,
// `Midyim`,
// `Mihalic Peynir`,
// `Milleens`,
// `Mimolette`,
// `Mine-Gabhar`,
// `miner’s lettuce`,
// `Mini Baby Bells`,
// `Minikin Pumpkin`,
// `Mint`,
// `Miracle fruit`,
// `Mixte`,
// `Mizuna Greens`,
// `Mock Buckthorn`,
// `Mock strawberry`,
// `Molbo`,
// `Mollusca`,
// `Momordica fruit`,
// `Monastery Cheeses`,
// `Mondseer`,
// `mongongo`,
// `Monguete`,
// `Monkey Apple`,
// `Monkfish`,
// `monks cress.`,
// `Monstera`,
// `Monstera deliciosa`,
// `Mont D'or Lyonnais`,
// `Montasio`,
// `Monterey Jack`,
// `Monterey Jack Dry`,
// `Möpkenbrot`,
// `Morbier`,
// `Morbier Cru de Montagne`,
// `Morcilla`,
// `Morcón`,
// `Morel`,
// `Morinda`,
// `Moronga`,
// `Morrpølse`,
// `Mortadella`,
// `Morteau sausage`,
// `Moth bean`,
// `Moth Orchid`,
// `Mothais a la Feuille`,
// `Mountain Pepper`,
// `Mountain Pepper`,
// `Mountain Soursop`,
// `Mouse melon`,
// `mozuku`,
// `Mozzarella`,
// `Mozzarella di Bufala`,
// `Mozzarella Fresh`,
// `Mozzarella Rolls`,
// `Muenster`,
// `Mulberry`,
// `Mullet`,
// `Mundu`,
// `Mung Bean`,
// `mung beans`,
// `Muntries`,
// `Murol`,
// `Mushroom`,
// `mushrooms`,
// `Musk melon`,
// `Muskmelon`,
// `Muskmelons`,
// `Mussel`,
// `Must melon`,
// `Mustamakkara`,
// `Mustard`,
// `mustard greens`,
// `Mycella`,
// `Myrtle`,
// `Myśliwska`,
// `Myzithra`,
// `Naboulsi`,
// `Nădlac sausage`,
// `Naem`,
// `Nageia`,
// `Nance`,
// `Nannyberry`,
// `Nantais`,
// `Napa Cabbage`,
// `Naples Cos`,
// `Naranja`,
// `Naranjilla`,
// `Native Cherry`,
// `Native Currant`,
// `Native Gooseberry`,
// `Nautilus`,
// `Navette`,
// `navy beans`,
// `Nduja`,
// `'Nduja`,
// `Nectarine`,
// `Neem`,
// // `Nem nướng`,
// `nettles`,
// `Neufchatel`,
// `New Potato`,
// `New Zealand Spinach`,
// `Newmarket sausage`,
// `Nigella`,
// `Niolo`,
// `Nokkelost`,
// `Noni fruit`,
// `Nopal`,
// `Northumberland`,
// `Noumboulo`,
// `Nungu`,
// `Nürnberger Bratwürste`,
// `Nutmeg`,
// `Nuvole`,
// `Oakleaf Lettuce`,
// `Oaxaca`,
// `oca`,
// `Octopus`,
// `ogonori`,
// `Oil Palm`,
// `okra`,
// `Olallieberry`,
// `Old World Sycomore`,
// `Olde York`,
// `Olive`,
// `Olivet au Foin`,
// `Olivet Bleu`,
// `Olivet Cendre`,
// `onion`,
// `onions`,
// `orach`,
// `Orache`,
// `Orange`,
// `Orange roughy`,
// `Orangelo`,
// `Oranges`,
// `orchid tree`,
// `Orecchiette`,
// `Oregano`,
// `Oregon Grape`,
// `Orkney Extra Mature Cheddar`,
// `Orla`,
// `Orris Root`,
// `Osage orange`,
// `Oschtjepka`,
// `Ossau Fermier`,
// `Ossau-Iraty`,
// `Ossenworst`,
// // `Ostravská klobása`,
// `Oszczypek`,
// `Otaheite Apple`,
// `Oxford Blue`,
// `Oxford sausage`,
// `Oyster`,
// `Oyster Plant`,
// `Paccheri`,
// `Pacific rudderfish`,
// `Pacific saury`,
// `Pacific snapper`,
// `Paio`,
// `Pak-Choi`,
// `Palet de Babligny`,
// `palm nuts`,
// `Palmetto`,
// `Pampanga longganisa`,
// `Paneer`,
// `Panela`,
// `Pannerone`,
// `Pansy`,
// `Pant ys Gawn`,
// `Papaya`,
// `Pappardelle`,
// `Paprika`,
// `paracress`,
// `Parmesan`,
// `Parmigiano Reggiano`,
// `Parrotfish`,
// `Parsley`,
// `parsnip`,
// `Parwal`,
// `Pas de l'Escalette`,
// `Passatelli`,
// `Passendale`,
// `Passion flower`,
// `Passion fruit`,
// `Passionfruit`,
// `Pasta al ceppo`,
// `Pasteurized Processed`,
// `Patagonian toothfish`,
// `Pate de Fromage`,
// `Patefine Fort`,
// `Pattypan Squash`,
// `Pave d'Affinois`,
// `Pave d'Auge`,
// `Pave de Chirac`,
// `Pave du Berry`,
// `Pawpaw`,
// `Pea`,
// `Peach`,
// `Peanut`,
// `Peanuts`,
// `Pear`,
// `peas`,
// `Pecans`,
// `Pecorino`,
// `Pecorino in Walnut Leaves`,
// `Pecorino Romano`,
// `Peekskill Pyramid`,
// `Pelardon des Cevennes`,
// `Pelardon des Corbieres`,
// `Penamellera`,
// `Penbryn`,
// `Pencarreg`,
// `Penne`,
// `Penne ricce`,
// `Pepper`,
// `Pepper Jack`,
// `Peppermint`,
// `Pepperoni`,
// `peppers`,
// `Pequi`,
// `Perail de Brebis`,
// `Perch`,
// `Perciatelli`,
// `Perennial Cucumber`,
// `Periwinkle`,
// `Persimmon`,
// `Petit Morin`,
// `Petit Pardou`,
// `Petit-Suisse`,
// `Pe-Tsai`,
// `Pewa`,
// `phalsa`,
// `Physalis`,
// `Picagge`,
// `Picchiarelli`,
// `Pici`,
// `Pick`,
// `Pickle`,
// `Pickling Onions`,
// `Picodon de Chevre`,
// `Picos de Europa`,
// `Pigeon Pea`,
// `Pigeon Plum`,
// `Pigface`,
// `pignut`,
// `Pike`,
// `Pilchard`,
// `Pili Nut`,
// `Pili Nuts`,
// `Pillus`,
// `Pinconning`,
// `Pine nuts`,
// `Pineapple`,
// `Pineapple guava`,
// `Pineapple sage`,
// `Pineberry`,
// `Pinkel`,
// `pinto beans`,
// `Pinuneg`,
// `Piora`,
// `Pipe rigate`,
// `Pistachios`,
// `Pitaya`,
// `Pithtviers au Foin`,
// `Pitomba`,
// `Pizzoccheri`,
// `Plaaswors`,
// `Plantain`,
// `Plateau de Herve`,
// `Plectranthus`,
// `Pleşcoi sausage`,
//     `Plinia`,
//     `Plum`,
//     `Plumcot`,
//     `Pluot`,
//     `Plymouth Cheese`,
//     `Podhalanski`,
//     `Podocarpus`,
//     `Poha`,
//     `Pois Doux`,
//     `Poivre d'Ane`,
//     `poke`,
//     `Polk`,
//     `Polkolbin`,
//     `Pollock`,
//     `Pomcite`,
//     `Pomegranate`,
//     `Pomelo`,
//     `Pomfret`,
//     `Pommecythere`,
//     `Pommerac`,
//     `Pompano`,
//     `Pond Apple`,
//     `Pont l'Eveque`,
//     `Poppy Seed`,
//     `Poppy seeds`,
//     `Poppyseed`,
//     `Pork and apple`,
//     `Pork and leek`,
//     `Pork sausage`,
//     `Port Nicholson`,
//     `Port-Salut`,
//     `Postel`,
//     `Potatiskorv`,
//     `potato`,
//     `Pouligny-Saint-Pierre`,
//     `Pourly`,
//     `prairie turnip`,
//     `Prasky`,
//     `Prastost`,
//     `Prawns`,
//     `Pressato`,
//     `Prickly Pear`,
//     `Prince-Jean`,
//     `Prinskorv`,
//     `Processed Cheddar`,
//     `Provel`,
//     `Provolone`,
//     `Prumnopitys`,
//     `Prune`,
//     `Prunes`,
//     `Prussian Asparagus`,
//     `P'tit Berrichon`,
//     `Pufferfish`,
//     `Pulasan`,
//     `Pummelo`,
//     `Pumpkin`,
//     `Pumpkin seeds`,
//     `Pupunha`,
//     `Purple Apple-Berry`,
//     `Purple bauhinia`,
//     `Purple mangosteen`,
//     `Purslane`,
//     `Pyengana Cheddar`,
//     `Pyramide`,
//     `Qazy`,
//     `Quadrefiore`,
//     `Quandong`,
//     `Quark`,
//     `Quartirolo Lombardo`,
//     `Quatre-Vents`,
//     `Quenepa`,
//     `Quercy Petit`,
//     `Queso Blanco`,
//     `Queso de Murcia`,
//     `Queso del Montsec`,
//     `Queso del Tietar`,
//     `Queso Fresco`,
//     `Queso Iberico`,
//     `Queso Jalapeno`,
//     `Queso Majorero`,
//     `Queso Media Luna`,
//     `Queso Para Frier`,
//     `Queso Quesadilla`,
//     `Quince`,
//     `Rabacal`,
//     `Raclette`,
//     `Radiatori`,
//     `radicchio`,
//     `Radiccio`,
//     `radish`,
//     `Ragusano`,
//     `Rainbow Chard`,
//     `Rainbow trout`,
//     `Raisin`,
//     `Raisins`,
//     `Rambutan`,
//     `Ramphal`,
//     `Rangpur`,
//     `Raschera`,
//     `Raspberries`,
//     `Raspberry`,
//     `Reblochon`,
//     `Red Bayberry`,
//     `red cabbage`,
//     `Red clover`,
//     `Red Kidney Beans`,
//     `Red Leicester`,
//     `Red Mombin`,
//     `Red Mulberry`,
//     `Red Pudding`,
//     `Redcurrant`,
//     `Regal de la Dombes`,
//     `Regensburger Wurst`,
//     `Reggianito`,
//     `Remedou`,
//     `Requeson`,
//     `rhubarb`,
//     `Riberry`,
//     `Riccioli`,
//     `Ricciolini`,
//     `Ricciutelle`,
//     `rice bean`,
//     `Richelieu`,
//     `Ricotta`,
//     `Ricotta Salata`,
//     `Ridder`,
//     `Ridge Cucumber`,
//     `Ridged Gourd`,
//     `Rigatoncini`,
//     `Rigatoni`,
//     `righteye flounder`,
//     `Rigotte`,
//     `Rimu`,
//     `Ringriderpølse`,
//     `Rocamadour`,
//     `rock cod`,
//     `Rock melon`,
//     `Rocket`,
//     `rockfish`,
//     `Rockmelon`,
//     `Rød pølse`,
//     `Roe`,
//     `Rollot`,
//     `Romaine Lettuce`,
//     `Romano`,
//     `Romans Part Dieu`,
//     `Rombi`,
//     `Roncal`,
//     `Rookworst`,
//     `Roquefort`,
//     `Rose`,
//     `Rose apple`,
//     `Rose Hip`,
//     `Rose Myrtle`,
//     `Rose-Leaf Bramble`,
//     `Rosemary`,
//     `Rosette de Lyon`,
//     `Rotelle`,
//     `Roule`,
//     `Rouleau De Beaulieu`,
//     `Rowan`,
//     `Royalp Tilsit`,
//     `Rubens`,
//     `Runner Bean`,
//     `runner beans`,
//     `Rustiche`,
//     `Rustinu`,
//     `rutabaga`,
//     `Ryynimakkara`,
//     `Saaland Pfarr`,
//     `Saanenkaese`,
//     `Sablefish`,
//     `Sabodet`,
//     `Sacha Inchi`,
//     `Sacred earflower`,
//     `Saffron`,
//     `Saga`,
//     `Sage`,
//     `Sage Derby`,
//     `Sageretia`,
//     `Sagnarelli`,
//     `Sagne 'ncannulate`,
//     `Sagnette`,
//     `Saguaro`,
//     `Sai gork`,
//     `Sai krok Isan`,
//     `Sai ua`,
//     `Sainte Maure`,
//     `Saint-Marcellin`,
//     `Saint-Nectaire`,
//     `Saint-Paulin`,
//     `Salak`,
//     `Salal Berry`,
//     `Salal berry`,
//     `Salami`,
//     `Salamin`,
//     `Salchicha`,
//     `Salchicha Huachana`,
//     `Salchichón`,
//     `Salers`,
//     `Salmonberry`,
//     `Salsichão`,
//     `salsify`,
//     `Salumi`,
//     `samphire`,
//     `Samso`,
//     `San Simon`,
//     `Sancerre`,
//     `Sanddab`,
//     `Sandpaper Fig`,
//     `Santol`,
//     `Sap Sago`,
//     `Sapodilla`,
//     `Sapota`,
//     `Sapote`,
//     `Sardel`,
//     `Sardelka`,
//     `Sardine`,

// ]
const ingredient = [
    // "Asado",
    // "Asado de tira",
    // "Bife de costilla",
    // "Bife de chorizo",
    // "Ojo de bife",
    // "Bola de lomo",
    // "Chinchulín",
    // "Colita de cuadril",
    // "Cuadril",
    // "Entraña",
    // "Falda",
    // "Lomo",
    // "Matambre",
    // "Mollejas",
    // "Pecho",
    // "Riñones",
    // "Tapa de asado",
    // "Tapa de nalga",
    // "Vacío",
    // `Acém`,
    // `Alcatra`,
    // `Contrafilé`,
    // `Coxão duro`,
    // `Coxão mole`,
    // `Filé Mignon`,
    // `Lagarto`,
    // `Maminha`,
    // `Patinho`,
    // `Picanha`,
    // `Cupim`,
    // `Fraldinha`,
    // `Paleta`,
    // `Tongue`,
    // `Necks`,
    // `Chuck`,
    // `Sirloin`,
    // `Rump`,
    // `Silverside`,
    // `Topside`,
    // `Top rump`,
    // `Fore rib`,
    // `Rib eye steak`,
    // `T-bone steak`,
    // `Thick rib`,
    // `Thin rib`,
    // `Brisket`,
    // `Shin and leg`,
    // `Flank`,
    // `Thick flank`,
    // `Feather blade`,
    // `Fillet`,
    // `Oxtail`,
    // `Milk`,
    // `Bread`,
    // `Butter`,
    // `Cheese`,
    // `Yogurt`,
    // `Sandwich`,
    // `Pancake`,
    // `Pie`,
    // `Honey`,
    // `Waffle`,
    // `Donuts`,
    // `Salad`,
    // `Meatball`,
    // `Grilled chicken`,
    // `Burger`,
    // `Tuna`,
    // `Noodles`,
    // `Egg`,
    // `Bacon`,
    // `Pizza`,
    // `French Fries`,
    // `Biryani`,
    // `Pasta`,
    // `Smoked salmon`,
    // `Mayonnaise`,
    // `Taco`,
    // `Hotdog`,
    // `Dosa`,
    // `Chocolate`,
    // `Ice cream`,
    // `Apples `,
    // ` Bananas `,
    // ` Pears `,
    // ` Apricots `,
    // ` Peaches `,
    // ` Plums `,
    // ` Avocados `,
    // ` Strawberries `,
    // ` Blueberries `,
    // ` Blackberries `,
    // ` Raspberries `,
    // ` Cherries `,
    // ` Mangos `,
    // ` Papayas `,
    // ` Lemons `,
    // ` Oranges `,
    // ` Grapefruit `,
    // ` Limes `,
    // ` Young coconut `,
    // ` Grapes `,
    // ` Tomatoes`,
    // `Asparagus `,
    // ` Eggplant `,
    // ` Spinach `,
    // ` Kale `,
    // ` Broccoli `,
    // ` Summer squash `,
    // ` Zucchini `,
    // ` Potatoes `,
    // ` Sweet potatoes `,
    // ` Jerusalem artichokes `,
    // ` Cucumbers `,
    // ` Lettuce `,
    // ` Onions `,
    // ` Garlic `,
    // ` Peppers `,
    // ` Cauliflower `,
    // ` Winter squash `,
    // ` Fiddleheads `,
    // ` Peas `,
    // ` Green beans `,
    // ` Wax beans `,
    // ` Corn`,
    // `Cashews `,
    // ` Almonds `,
    // ` Hazelnuts `,
    // ` Brazil nuts `,
    // ` Pecans `,
    // ` Walnuts `,
    // ` Pine nuts `,
    // ` Sunflower seeds `,
    // ` Sesame seeds `,
    // ` Pumpkin seeds `,
    // ` Hemp seeds `,
    // ` Flax seeds `,
    // ` Chia seeds`,
    // ` Garlic `,
    // ` Peppers `,
    // ` Cauliflower `,
    // ` Winter squash `,
    // ` Fiddleheads `,
    // ` Peas `,
    // ` Green beans `,
    // ` Wax beans `,
    // ` Corn`,
    // `Wheat `,
    // ` Rice `,
    // ` Buckwheat `,
    // ` Quinoa `,
    // ` Oats `,
    // ` Amaranth `,
    // ` Spelt `,
    // ` Rye `,
    // ` Barley `,
    // ` Teff`,
    // `Black beans `,
    // ` Kidney beans `,
    // ` White beans `,
    // ` Navy beans `,
    // ` Butter beans `,
    // ` Lentils `,
    // ` Chickpeas`,
    // ` Red beans `,
    // ` Peanuts`,
    // `garbanzo beans`,
    // `Olive oil `,
    // ` Coconut oil `,
    // ` Palm oil`,
    // `honey `,
    // `agave nectar `,
    // `maple syrup`,
    // `coconut milk`,
    // `coconut cream`,
    // `soy milk`,
    // `Vinegar`,
    // `Pickles`,
    // `Kimchee`,
    // `eggs`,
    // `Avocado`,
    // `Apple`,
    // `Banana`,
    // `Blueberries`,
    // `Cranberries`,
    // `Coconut`,
    // `Cherries`,
    // `Dragonfruit`,
    // `Figs`,
    // `Guava`,
    // `Grapefruit`,
    // `Grapes`,
    // `Kiwi`,
    // `Lychees`,
    // `Lemon`,
    // `Lime`,
    // `Mango`,
    // `Melon`,
    // `Mandarin`,
    // `Nectarine`,
    // `Olives`,
    // `Orange`,
    // `Pineapple`,
    // `Peach`,
    // `Plum`,
    // `Pomegranate`,
    // `Strawberries`,
    // `Water chestnuts`,
    // `Artichokes`,
    // `Asparagus`,
    // `Beets`,
    // `Bell peppers`,
    // `Bok Choy`,
    // `Broccoli`,
    // `Cabbage`,
    // `Carrots`,
    // `Cauliflower`,
    // `Celery`,
    // `Chard`,
    // `Chinese cabbage`,
    // `Corn`,
    // `Cucumbers`,
    // `Eggplants`,
    // `Fennel`,
    // `Garlic`,
    // `Ginger`,
    // `Horseradish`,
    // `Jicama`,
    // `Kale`,
    // `Kohlrabi`,
    // `Lettuce`,
    // `Leeks`,
    // `Mushrooms`,
    // `Onions`,
    // `Parsnips`,
    // `Peas`,
    // `Peppers`,
    // `Pumpkin`,
    // `Radish`,
    // `Rhubarb`,
    // `Rutabaga`,
    // `Sea Weeds`,
    // `Shallots`,
    // `Spinach`,
    // `Squash`,
    // `Sweet corn`,
    // `Sweet potatoes`,
    // `Tomatoes`,
    // `Turnips`,
    // `Yams`,
    // `Zucchini`,
    // `Basil`,
    // `Cayenne Pepper`,
    // `Celtic Sea Salt`,
    // `Cinnamon`,
    // `Cumin`,
    // `Chilli Powder`,
    // `Chives`,
    // `Coriander`,
    // `Ginger`,
    // `Mint`,
    // `Oregano`,
    // `Parsley`,
    // `Rosemary`,
    // `Thyme`,
    // `Almonds`,
    // `Brazil`,
    // `Cashews`,
    // `Chia`,
    // `Coconut`,
    // `Flax`,
    // `Hemp`,
    // `Macadamia`,
    // `Pecan`,
    // `Sesame`,
    // `Sunflower`,
    // `Walnut`,
    // `Alfalfa`,
    // `Barley Grass`,
    // `Wheat Grass`,
    // `Buckwheat`,
    // `Barely`,
    // `Oats`,
    // `Adzuki Beans`,
    // `Chickpeas`,
    // `Mung Beans`,
    // `Coconut`,
    // `Chia`,
    // `Cold Pressed Olive`,
    // `Sugarcane`,
    // `Honey`,
    // `Coconut nectar`,
    // `Yacon syrup`,
    // `Date sugar`,
    // `Barley grass`,
    // `Vegetable or fruit juice`,
    // `Young coconut water`,
    // `Wheatgrass`,
    // `Cooked fruits`,
    // `Cooked vegetables`,
    // `Cooked Meats`,
    // `Baked items`,
    // `Roasted nuts and seeds`,
    // `Refined Oils`,
    // `Table salt`,
    // `Refined sugars and flour`,
    // `Pasteurized juices and dairy`,
    // `Coffee and tea`,
    // `Alcohol`,
    // `Pasta`,
    // `Pastries`,
    // `Chips`,
    // `Processed foods and snacks`,



]
const getNutrition = async (req, res) => {
    // const { ingredient } = req.params
    // console.log(ingredient)
    // console.log(req.body)
    try {

        for (const item of ingredient) {
            console.log(item)
            const result = await nutritionLogic.search(item);
            postIngredient(result)
            await new Promise(resolve => setTimeout(resolve, 5000)); // Wait for 5 seconds before fetching next item
        }

        // const result = await nutritionLogic.search(ingredient);

        // console.log("getNutrition res", result);
        // postIngredient(result)
        // res.status(200).send(result);

    } catch (error) {
        res.status(500).send("/search something went wrong", error);
    }
}

const postIngredient = async (data) => {
    console.log(data.items[0])

    await nutritionLogic.postIngredient(data);

}

// getNutrition()


module.exports = { getNutrition, postIngredient }

// for (const item of ingredient) {
//         await nutritionLogic.search(item);
//         await new Promise(resolve => setTimeout(resolve, 10000)); // Wait for 5 seconds before fetching next item
//     }